// Package hostwrap generates and resolves the HOST launch wrappers described in
// docs/design/host-agent-environment.md §5.1.
//
// A wrapper is a three-line shell script named after a program a selected pack installs.
// It holds no logic — it execs `yolo host -- <program> "$@"` — because there must be
// exactly one implementation of environment composition (§1 P4). Everything about which
// environment a launch gets is decided inside `yolo host` at LAUNCH time, from live
// config; the wrapper decides nothing.
//
// # Why every program gets one, including programs that need no environment
//
// The wrap directory is an ADDRESSABLE LAUNCH SURFACE, the way a mise or asdf shim
// directory is: the shim for every installed tool exists unconditionally, so a script or
// an IDE's "agent binary" setting can point at `<wrap dir>/<program>` by absolute path
// and rely on getting a correct environment regardless of shell config. A wrapper set
// computed from what a config happens to resolve to would exist on some machines and not
// others, which is not a surface (§5.4, OQ-5). The only thing that decides whether a
// wrapper exists is whether a selected pack installs that program.
package hostwrap

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/mschulkind-oss/yolo-jail/internal/packload"
	"github.com/mschulkind-oss/yolo-jail/internal/shquote"
)

// Body returns the exact contents of the wrapper for program bin.
//
// The target is named, never path-resolved here: `yolo host` resolves it at launch while
// skipping yolo's own directories (LookPathSkipping), which is what stops the wrapper
// from exec'ing itself. Hard-coding a path instead would also break the moment
// `claude update` moved the binary.
func Body(bin string) string {
	return "#!/usr/bin/env bash\n" +
		"# Generated by yolo — host launch wrapper. Do not edit; `yolo host apply` rewrites it.\n" +
		"exec yolo host -- " + shquote.Quote(bin) + " \"$@\"\n"
}

// Bins returns the sorted, de-duplicated set of programs that should have a wrapper,
// given the selected packs.
//
// HonoredInstalls applies the per-contribution origin gate: a FETCHED pack cannot
// introduce a curl-piped installer, and a program yolo would refuse to install is one it
// must not advertise a launcher for either. Refusals are reported at staging/apply time,
// not here.
func Bins(packs []*packload.Pack) []string {
	seen := map[string]bool{}
	var out []string
	for _, p := range packs {
		if p == nil {
			continue
		}
		installs, _ := p.HonoredInstalls()
		for _, in := range installs {
			if in.Bin == "" || seen[in.Bin] {
				continue
			}
			seen[in.Bin] = true
			out = append(out, in.Bin)
		}
	}
	sort.Strings(out)
	return out
}

// Plan is what a Generate would do, and what it did. Wrappers names the full intended
// set; Added and Removed are the delta against what is already on disk.
type Plan struct {
	Dir      string
	Wrappers []string
	Added    []string
	Removed  []string
	// Rewritten names wrappers whose body changed (a yolo upgrade that changes Body).
	Rewritten []string
}

// Changed reports whether applying this plan alters the directory's contents. `apply`
// prints the PATH line exactly when this is true — a completion notice about its own
// action, which needs to know nothing about the user's shell or RC file (§5.5, OQ-4).
func (p Plan) Changed() bool {
	return len(p.Added) > 0 || len(p.Removed) > 0 || len(p.Rewritten) > 0
}

// PlanFor computes the delta between the wanted wrapper set and what dir holds now.
// A dir that does not exist yet yields every wrapper as Added.
func PlanFor(dir string, bins []string) (Plan, error) {
	p := Plan{Dir: dir, Wrappers: bins}
	want := map[string]bool{}
	for _, b := range bins {
		want[b] = true
	}
	existing, err := os.ReadDir(dir)
	if err != nil {
		if !os.IsNotExist(err) {
			return p, err
		}
		p.Added = append([]string(nil), bins...)
		return p, nil
	}
	have := map[string]bool{}
	for _, e := range existing {
		if e.IsDir() {
			continue
		}
		have[e.Name()] = true
		if !want[e.Name()] {
			p.Removed = append(p.Removed, e.Name())
		}
	}
	for _, b := range bins {
		if !have[b] {
			p.Added = append(p.Added, b)
			continue
		}
		got, err := os.ReadFile(filepath.Join(dir, b))
		if err != nil || string(got) != Body(b) {
			p.Rewritten = append(p.Rewritten, b)
		}
	}
	sort.Strings(p.Removed)
	return p, nil
}

// Generate makes dir's contents exactly the wrappers for bins, and returns what it did.
//
// The directory is reset CONTENTS-ONLY — never RemoveAll. Prepending it to PATH means a
// user's shell (and, on a self-hosting machine, a live jail's bind mount) has captured
// this directory's identity; unlinking and recreating it would hand back a new inode and
// silently detach every one of those references. It is the same invariant the jail's
// generated-script anchors follow.
func Generate(dir string, bins []string) (Plan, error) {
	plan, err := PlanFor(dir, bins)
	if err != nil {
		return plan, err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return plan, fmt.Errorf("creating the wrapper directory: %w", err)
	}
	for _, name := range plan.Removed {
		if err := os.Remove(filepath.Join(dir, name)); err != nil && !os.IsNotExist(err) {
			return plan, fmt.Errorf("removing stale wrapper %s: %w", name, err)
		}
	}
	for _, bin := range bins {
		path := filepath.Join(dir, bin)
		// 0o755: it has to be executable to be on PATH at all.
		if err := os.WriteFile(path, []byte(Body(bin)), 0o755); err != nil {
			return plan, fmt.Errorf("writing wrapper %s: %w", bin, err)
		}
	}
	return plan, nil
}

// Clear empties dir's contents without removing dir itself — what an apply does when the
// opt-in has been turned back off. A directory that never existed is not an error.
func Clear(dir string) (Plan, error) {
	plan, err := PlanFor(dir, nil)
	if err != nil {
		return plan, err
	}
	for _, name := range plan.Removed {
		if err := os.Remove(filepath.Join(dir, name)); err != nil && !os.IsNotExist(err) {
			return plan, fmt.Errorf("removing wrapper %s: %w", name, err)
		}
	}
	return plan, nil
}

// PathLine is the single line a user adds to their shell rc to make wrappers take effect.
//
// It PREPENDS. Appending puts the wrapper behind the real binary and it never runs — and
// the real binary is genuinely there: claude's own installer writes ~/.local/bin/claude,
// which is why wrappers need a directory of their own rather than that one (§5.1).
func PathLine(dir string) string {
	return `export PATH="` + dir + `:$PATH"`
}

// OnPath reports whether dir is an entry in pathEnv (a PATH-formatted string).
//
// Entries are compared after cleaning, so a trailing slash or a "." segment does not
// produce a false negative. This is only ever used by `yolo check`, which runs from a
// fresh shell and so gets a decidable answer; `apply` deliberately never asks, because
// the PATH it can see is a fact about the shell that invoked it rather than about the
// user's rc file (§5.5).
func OnPath(pathEnv, dir string) bool {
	want := filepath.Clean(dir)
	for _, entry := range filepath.SplitList(pathEnv) {
		if entry == "" {
			continue
		}
		if filepath.Clean(entry) == want {
			return true
		}
	}
	return false
}

// LookPathSkipping resolves bin against pathEnv, ignoring any directory under one of
// skipRoots.
//
// This is the RECURSION GUARD, and it is load-bearing for the whole wrapper design: the
// wrapper `<wrap dir>/claude` execs `yolo host -- claude`, so if `yolo host` resolved
// "claude" the ordinary way it would find the wrapper again and fork-bomb. Skipping
// yolo's own generated directories is what makes the three-line wrapper safe, and it is
// the reason wrappers can hold no logic. Narrowing this guard breaks the wrapper front
// door first and loudly.
//
// Returns the resolved absolute path, or an error naming what was searched.
func LookPathSkipping(pathEnv, bin string, skipRoots []string) (string, error) {
	if bin == "" {
		return "", fmt.Errorf("no command given")
	}
	// An explicit path (contains a separator) is honored as-is: the user named a file,
	// not a PATH lookup, and second-guessing that would be surprising.
	if strings.ContainsRune(bin, filepath.Separator) {
		if err := executable(bin); err != nil {
			return "", err
		}
		abs, err := filepath.Abs(bin)
		if err != nil {
			return bin, nil //nolint:nilerr // a non-absolutizable path is still usable
		}
		return abs, nil
	}
	var cleanSkips []string
	for _, r := range skipRoots {
		if r != "" {
			cleanSkips = append(cleanSkips, filepath.Clean(r))
		}
	}
	var searched []string
	for _, dir := range filepath.SplitList(pathEnv) {
		if dir == "" {
			continue
		}
		clean := filepath.Clean(dir)
		if underAny(clean, cleanSkips) {
			continue
		}
		searched = append(searched, clean)
		candidate := filepath.Join(clean, bin)
		if err := executable(candidate); err == nil {
			return candidate, nil
		}
	}
	if len(searched) == 0 {
		return "", fmt.Errorf("%s: not found (no usable PATH entries outside yolo's own directories)", bin)
	}
	return "", fmt.Errorf("%s: not found in PATH (searched %d directories, skipping yolo's own)",
		bin, len(searched))
}

// underAny reports whether path is one of roots or lives beneath one.
func underAny(path string, roots []string) bool {
	for _, root := range roots {
		if path == root || strings.HasPrefix(path, root+string(filepath.Separator)) {
			return true
		}
	}
	return false
}

// executable reports whether path is an existing regular file with an execute bit.
func executable(path string) error {
	info, err := os.Stat(path)
	if err != nil {
		return err
	}
	if info.IsDir() {
		return fmt.Errorf("%s: is a directory", path)
	}
	if info.Mode()&0o111 == 0 {
		return fmt.Errorf("%s: not executable", path)
	}
	return nil
}
