// Package hostwrap generates and resolves the HOST launch wrappers described in
// docs/reference/host-agent-environment.md §5.1.
//
// A wrapper is a three-line shell script named after a program a selected pack installs.
// It holds no logic — it execs `<yolo> host -- <program> "$@"`, naming the yolo that wrote
// it by absolute path — because there must be exactly one implementation of environment
// composition (§1 P4). Everything about which environment a launch gets is decided inside
// `yolo host` at LAUNCH time, from live config; the wrapper decides nothing.
//
// # Why the wrapper names yolo by absolute path
//
// An IDE or a desktop launcher starts a program with the PATH its own launcher handed it,
// which on either OS is not the PATH a shell rc builds: a launchd- or desktop-spawned app
// never reads the rc. A wrapper that found yolo through PATH therefore exited 127
// ("exec: yolo: not found") at exactly the launch the absolute-path surface below exists
// for. The spelling is Running's: the applier's PATH spelling when it names the running
// file, so a package manager's stable link is baked rather than a versioned path an upgrade
// deletes, and an existing wrapper naming the same file keeps its spelling (PlanFor).
//
// # Why every program gets one, including programs that need no environment
//
// The wrap directory is an ADDRESSABLE LAUNCH SURFACE, the way a mise or asdf shim
// directory is: the shim for every installed tool exists unconditionally, so a script or
// an IDE's "agent binary" setting can point at `<wrap dir>/<program>` by absolute path
// and rely on getting a correct environment regardless of shell config. A wrapper set
// computed from what a config happens to resolve to would exist on some machines and not
// others, which is not a surface (§5.4, OQ-5). The only thing that decides whether a
// wrapper exists is whether a selected pack installs that program.
package hostwrap

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/sys/unix"

	"github.com/mschulkind-oss/yolo-jail/internal/packdecl"
	"github.com/mschulkind-oss/yolo-jail/internal/packload"
	"github.com/mschulkind-oss/yolo-jail/internal/shquote"
)

// bodyHeader is every wrapper's first two lines.
const bodyHeader = "#!/usr/bin/env bash\n" +
	"# Generated by yolo — host launch wrapper. Do not edit; `yolo host apply` rewrites it.\n"

// BodyFor returns the exact contents of the wrapper for program bin, which execs the yolo at
// yolo.
//
// The PROGRAM is named, never path-resolved here: `yolo host` resolves it at launch while
// skipping yolo's own directories (LookPathSkipping), which is what stops the wrapper from
// exec'ing itself. Hard-coding its path instead would also break the moment `claude update`
// moved the binary. YOLO is the opposite case, and is named by path (see the package doc): it
// is the one program the wrapper itself has to find, from a PATH nobody composed.
func BodyFor(yolo, bin string) string {
	return bodyHeader + "exec " + shquote.Quote(yolo) + " host -- " + shquote.Quote(bin) + " \"$@\"\n"
}

// Body is the wrapper for bin that an apply by this process writes into an empty wrapper
// directory: BodyFor naming Running over this process's PATH.
func Body(bin string) string { return BodyFor(Running(os.Getenv("PATH")), bin) }

// NamedYolo returns the yolo a wrapper body execs, and false when body is not exactly a body
// BodyFor writes for bin — a hand-edited file, or some other script. A body an older yolo wrote
// names `yolo` bare, which is returned as written.
func NamedYolo(body, bin string) (string, bool) {
	rest, ok := strings.CutPrefix(body, bodyHeader+"exec ")
	if !ok {
		return "", false
	}
	quoted, ok := strings.CutSuffix(rest, " host -- "+shquote.Quote(bin)+" \"$@\"\n")
	if !ok {
		return "", false
	}
	yolo := quoted
	if len(quoted) >= 2 && strings.HasPrefix(quoted, "'") && strings.HasSuffix(quoted, "'") {
		yolo = strings.ReplaceAll(quoted[1:len(quoted)-1], `'"'"'`, "'")
	}
	// The round trip is the parse's proof: anything BodyFor would not write back byte for
	// byte is not a wrapper this package wrote.
	if yolo == "" || BodyFor(yolo, bin) != body {
		return "", false
	}
	return yolo, true
}

// Running is how a wrapper written by this process names it: Spelling over the running
// executable and pathEnv, or the bare name `yolo` when os.Executable cannot answer.
func Running(pathEnv string) string {
	exe, err := os.Executable()
	if err != nil {
		return "yolo"
	}
	return Spelling(exe, pathEnv)
}

// Spelling is how a wrapper names the yolo at exe: the first absolute pathEnv entry whose `yolo`
// IS exe (os.SameFile), and otherwise exe itself, cleaned.
//
// The PATH spelling comes first because of what an upgrade does to the other one. A package
// manager links a stable name (Homebrew's /opt/homebrew/bin/yolo) to a versioned file the next
// upgrade deletes, and os.Executable may answer with either: Linux reads /proc/self/exe and
// resolves the link, darwin reports the path the process was started by. Any entry naming the
// running file counts, not just the first `yolo` on PATH, so a second yolo earlier on PATH
// never decides the spelling of this one. A relative entry is skipped: what it names depends on
// the directory the apply ran in.
//
// An exe that cannot be stat'd (deleted while it runs, and not replaced) names nothing a
// wrapper could exec, so the answer is the bare name `yolo`: the spelling every wrapper had
// before wrappers named yolo by path, which still runs wherever PATH finds a yolo.
func Spelling(exe, pathEnv string) string {
	if abs, err := filepath.Abs(exe); err == nil {
		exe = abs
	}
	exe = filepath.Clean(exe)
	exeInfo, err := os.Stat(exe)
	if err != nil {
		return "yolo"
	}
	for _, dir := range filepath.SplitList(pathEnv) {
		if dir == "" || !filepath.IsAbs(dir) {
			continue
		}
		candidate := filepath.Join(filepath.Clean(dir), "yolo")
		if info, err := os.Stat(candidate); err == nil && os.SameFile(info, exeInfo) {
			return candidate
		}
	}
	return exe
}

// Runnable reports why the file at path cannot be exec'd by this process, or nil when it can:
// the lookup's own test (an existing regular file, an execute bit, and access(2) for the
// effective user), for `yolo check` to ask of the yolo a wrapper names.
func Runnable(path string) error {
	if err := executable(path); err != nil {
		return err
	}
	if !canExecute(path) {
		return fmt.Errorf("%s: permission denied", path)
	}
	return nil
}

// Bins returns the sorted, de-duplicated set of programs that should have a wrapper,
// given the selected packs.
//
// HonoredInstalls applies the per-contribution origin gate: a FETCHED pack cannot
// introduce a curl-piped installer, and a program yolo would refuse to install is one it
// must not advertise a launcher for either. Refusals are reported at staging/apply time,
// not here.
//
// A bin that is not a bare program name (packdecl.ValidBinName) is skipped for the same
// reason: a wrapper is FILED at filepath.Join(dir, bin), and the schema's refusal is only
// as good as the loader the pack came through.
func Bins(packs []*packload.Pack) []string {
	seen := map[string]bool{}
	var out []string
	for _, p := range packs {
		if p == nil {
			continue
		}
		installs, _ := p.HonoredInstalls()
		for _, in := range installs {
			if !packdecl.ValidBinName(in.Bin) || seen[in.Bin] {
				continue
			}
			seen[in.Bin] = true
			out = append(out, in.Bin)
		}
	}
	sort.Strings(out)
	return out
}

// Plan is what a Generate would do, and what it did. Wrappers names the full intended
// set; Added and Removed are the delta against what is already on disk.
type Plan struct {
	Dir      string
	Wrappers []string
	Added    []string
	Removed  []string
	// Rewritten names wrappers whose body changed: a yolo upgrade that changes BodyFor, or a
	// wrapper naming a yolo that is not the file the apply runs.
	Rewritten []string
}

// Changed reports whether applying this plan alters the directory's contents. `apply`
// prints the PATH line exactly when this is true — a completion notice about its own
// action, which needs to know nothing about the user's shell or RC file (§5.5, OQ-4).
func (p Plan) Changed() bool {
	return len(p.Added) > 0 || len(p.Removed) > 0 || len(p.Rewritten) > 0
}

// PlanFor computes the delta between the wanted wrapper set — each execing the yolo at yolo
// (BodyFor) — and what dir holds now. A dir that does not exist yet yields every wrapper as
// Added.
//
// A wrapper whose body names ANOTHER SPELLING OF THE SAME FILE as yolo is unchanged, not
// Rewritten: the launch gate's apply runs from whatever PATH launched the agent, so a spelling
// that followed the applier would rewrite the wrappers, and stop the launch to say so, every
// time two shells spell one yolo differently. Same-file is decided by os.SameFile on the two
// paths as they stand; a named yolo that no longer exists is never the same file, so the next
// apply repairs it.
func PlanFor(dir, yolo string, bins []string) (Plan, error) {
	p, _, err := planFor(dir, yolo, bins)
	return p, err
}

// planFor is PlanFor, also returning the spelling a wrapper it adds or rewrites names yolo by:
// the one an existing wrapper gives the same file (adoptedSpelling), else yolo as given.
func planFor(dir, yolo string, bins []string) (Plan, string, error) {
	p := Plan{Dir: dir, Wrappers: bins}
	want := map[string]bool{}
	for _, b := range bins {
		want[b] = true
	}
	existing, err := os.ReadDir(dir)
	if err != nil {
		if !os.IsNotExist(err) {
			return p, yolo, err
		}
		p.Added = append([]string(nil), bins...)
		return p, yolo, nil
	}
	spelling := adoptedSpelling(dir, existing, yolo)
	have := map[string]bool{}
	for _, e := range existing {
		if e.IsDir() {
			continue
		}
		have[e.Name()] = true
		if !want[e.Name()] {
			p.Removed = append(p.Removed, e.Name())
		}
	}
	for _, b := range bins {
		if !have[b] {
			p.Added = append(p.Added, b)
			continue
		}
		got, err := os.ReadFile(filepath.Join(dir, b))
		if err != nil || !current(string(got), yolo, b) {
			p.Rewritten = append(p.Rewritten, b)
		}
	}
	sort.Strings(p.Removed)
	return p, spelling, nil
}

// adoptedSpelling is the spelling the first existing wrapper (in name order) gives the file at
// yolo, or yolo itself when none names that file. A wrapper an apply adds or rewrites takes it,
// so a pack added while the agents launch from a PATH that spells yolo another way (an IDE's,
// or Linux's resolved Homebrew path) gets the spelling the directory already uses, not the one
// an upgrade deletes.
func adoptedSpelling(dir string, existing []os.DirEntry, yolo string) string {
	for _, e := range existing {
		if e.IsDir() {
			continue
		}
		body, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			continue
		}
		if named, ok := NamedYolo(string(body), e.Name()); ok && sameExistingYolo(named, yolo) {
			return named
		}
	}
	return yolo
}

// current reports whether body is the wrapper for bin execing yolo: BodyFor's bytes, or a body
// BodyFor wrote for another absolute spelling of the same file (PlanFor says why).
func current(body, yolo, bin string) bool {
	if body == BodyFor(yolo, bin) {
		return true
	}
	named, ok := NamedYolo(body, bin)
	return ok && sameExistingYolo(named, yolo)
}

// sameExistingYolo reports whether a and b are absolute paths naming one file that exists. Unlike
// sameFile, two spellings of a file that is gone are never the same: a wrapper naming a yolo that
// is gone is one an apply rewrites.
func sameExistingYolo(a, b string) bool {
	if !filepath.IsAbs(a) || !filepath.IsAbs(b) {
		return false
	}
	ai, aerr := os.Stat(a)
	bi, berr := os.Stat(b)
	return aerr == nil && berr == nil && os.SameFile(ai, bi)
}

// Generate makes dir's contents exactly the wrappers for bins, each execing the yolo at yolo,
// and returns what it did. It writes the plan's Added and Rewritten wrappers and nothing else, so
// a wrapper PlanFor calls unchanged — one naming another spelling of the same yolo included —
// keeps its bytes, and a wrapper it writes names yolo the way the directory already does
// (adoptedSpelling).
//
// The directory is reset CONTENTS-ONLY — never RemoveAll. Prepending it to PATH means a
// user's shell (and, on a self-hosting machine, a live jail's bind mount) has captured
// this directory's identity; unlinking and recreating it would hand back a new inode and
// silently detach every one of those references. It is the same invariant the jail's
// generated-script anchors follow.
func Generate(dir, yolo string, bins []string) (Plan, error) {
	plan, spelling, err := planFor(dir, yolo, bins)
	if err != nil {
		return plan, err
	}
	// The traversal guard, stated at the writer and ahead of every write: the loop below
	// writes filepath.Join(dir, bin), and the wrap dir is PREPENDED to the user's PATH, so a
	// bin carrying path structure must never get there. Bins already filters; refusing here
	// (rather than skipping) is what makes a bypassing caller loud instead of quietly
	// under-generated.
	for _, bin := range bins {
		if !packdecl.ValidBinName(bin) {
			return plan, fmt.Errorf("refusing to write wrapper %q: bin must be a bare program name", bin)
		}
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return plan, fmt.Errorf("creating the wrapper directory: %w", err)
	}
	for _, name := range plan.Removed {
		if err := os.Remove(filepath.Join(dir, name)); err != nil && !os.IsNotExist(err) {
			return plan, fmt.Errorf("removing stale wrapper %s: %w", name, err)
		}
	}
	for _, bin := range append(append([]string(nil), plan.Added...), plan.Rewritten...) {
		path := filepath.Join(dir, bin)
		// 0o755: it has to be executable to be on PATH at all.
		if err := os.WriteFile(path, []byte(BodyFor(spelling, bin)), 0o755); err != nil {
			return plan, fmt.Errorf("writing wrapper %s: %w", bin, err)
		}
	}
	return plan, nil
}

// Clear empties dir's contents without removing dir itself — what an apply does when the
// opt-in has been turned back off. A directory that never existed is not an error.
func Clear(dir string) (Plan, error) {
	plan, err := PlanFor(dir, "", nil)
	if err != nil {
		return plan, err
	}
	for _, name := range plan.Removed {
		if err := os.Remove(filepath.Join(dir, name)); err != nil && !os.IsNotExist(err) {
			return plan, fmt.Errorf("removing wrapper %s: %w", name, err)
		}
	}
	return plan, nil
}

// PathLine is the single line a user adds to their shell rc to make wrappers take effect.
//
// It PREPENDS. Appending puts the wrapper behind the real binary and it never runs — and
// the real binary is genuinely there: claude's own installer writes ~/.local/bin/claude,
// which is why wrappers need a directory of their own rather than that one (§5.1).
func PathLine(dir string) string {
	return `export PATH="` + dir + `:$PATH"`
}

// OnPath reports whether dir is an entry in pathEnv (a PATH-formatted string).
//
// Entries are compared after cleaning, so a trailing slash or a "." segment does not
// produce a false negative. This is only ever used by `yolo check`, which runs from a
// fresh shell and so gets a decidable answer; `apply` deliberately never asks, because
// the PATH it can see is a fact about the shell that invoked it rather than about the
// user's rc file (§5.5).
//
// An entry that SPELLS the directory differently but IS it — a symlinked parent, which is
// what macOS's /var -> /private/var makes of every temp path — also counts: the question is
// whether a lookup through that entry reaches the wrappers, and it does. Spelling-only
// comparison reported such a PATH as "NOT on PATH" while the shell ran the wrappers fine.
func OnPath(pathEnv, dir string) bool {
	want := filepath.Clean(dir)
	wantInfo, wantErr := os.Stat(want)
	for _, entry := range filepath.SplitList(pathEnv) {
		if entry == "" {
			continue
		}
		clean := filepath.Clean(entry)
		if clean == want {
			return true
		}
		if wantErr != nil {
			continue
		}
		if info, err := os.Stat(clean); err == nil && os.SameFile(info, wantInfo) {
			return true
		}
	}
	return false
}

// Resolve answers "what does a bare `bin` run?" against pathEnv the way a shell's command
// lookup does: the FIRST PATH entry holding an executable of that name wins, and nothing
// after it is consulted. It returns the path found through the PATH entry as spelled, and
// false when nothing on PATH provides bin.
//
// It is LookPathSkipping with nothing skipped — deliberately the same lookup the wrapper's
// exec half uses, so "which binary wins" and "which binary `yolo host` would exec" cannot
// come to disagree about what counts as runnable. One divergence from a shell is inherited
// and stated: an EMPTY PATH entry means "the current directory" to POSIX sh and is skipped
// here, because the answer would depend on where `yolo check` happened to be run from.
func Resolve(pathEnv, bin string) (string, bool) {
	if bin == "" || strings.ContainsRune(bin, filepath.Separator) {
		return "", false
	}
	p, err := LookPathSkipping(pathEnv, bin, nil)
	if err != nil {
		return "", false
	}
	return p, true
}

// Shadow is a wrapper that does NOT win PATH lookup for its own name.
type Shadow struct {
	// Bin is the wrapper's (and the program's) name.
	Bin string
	// Winner is what a bare Bin runs instead, as found on PATH. "" means nothing on PATH
	// provides Bin at all — the wrapper itself is not runnable from there.
	Winner string
}

// Precedence splits bins — wrappers generated in dir — into the ones a bare invocation
// reaches (wins) and the ones something earlier on pathEnv shadows.
//
// ON PATH IS NOT THE SAME AS WINNING, which is the whole reason this exists beside OnPath:
// a wrap dir APPENDED to PATH is on it, and every wrapper whose program is also installed
// earlier on PATH (claude's own installer writes ~/.local/bin/claude) never runs. That is
// the "Prepend, not append" rule (docs/reference/host-agent-environment.md), observed.
//
// Winning is decided by FILE IDENTITY (os.SameFile), not by comparing path strings: the
// PATH entry and dir may spell one directory two ways (a symlinked parent — every macOS
// temp path, /var being a symlink to /private/var), and a PATH-side symlink that points at
// the wrapper runs the wrapper. Either way the question is what executes, and that is a
// property of the file.
func Precedence(pathEnv, dir string, bins []string) (wins []string, shadowed []Shadow) {
	for _, bin := range bins {
		winner, ok := Resolve(pathEnv, bin)
		if !ok {
			shadowed = append(shadowed, Shadow{Bin: bin})
			continue
		}
		if sameFile(winner, filepath.Join(dir, bin)) {
			wins = append(wins, bin)
			continue
		}
		shadowed = append(shadowed, Shadow{Bin: bin, Winner: winner})
	}
	return wins, shadowed
}

// sameFile reports whether a and b name one file, following symlinks. A path that cannot be
// stat'd is compared by its cleaned spelling, so a vanished file is never "the same" as a
// different one.
func sameFile(a, b string) bool {
	ai, aerr := os.Stat(a)
	bi, berr := os.Stat(b)
	if aerr != nil || berr != nil {
		return filepath.Clean(a) == filepath.Clean(b)
	}
	return os.SameFile(ai, bi)
}

// LookPathSkipping resolves bin against pathEnv, ignoring any directory under one of
// skipRoots.
//
// This is the RECURSION GUARD, and it is load-bearing for the whole wrapper design: the
// wrapper `<wrap dir>/claude` execs `<yolo> host -- claude`, so if `yolo host` resolved
// "claude" the ordinary way it would find the wrapper again and fork-bomb. Skipping
// yolo's own generated directories is what makes the three-line wrapper safe, and it is
// the reason wrappers can hold no logic. Narrowing this guard breaks the wrapper front
// door first and loudly.
//
// Returns the resolved absolute path, or an error naming what was searched.
func LookPathSkipping(pathEnv, bin string, skipRoots []string) (string, error) {
	if bin == "" {
		return "", fmt.Errorf("no command given")
	}
	// An explicit path (contains a separator) is honored as-is: the user named a file,
	// not a PATH lookup, and second-guessing that would be surprising.
	if strings.ContainsRune(bin, filepath.Separator) {
		if err := executable(bin); err != nil {
			return "", err
		}
		abs, err := filepath.Abs(bin)
		if err != nil {
			return bin, nil //nolint:nilerr // a non-absolutizable path is still usable
		}
		return abs, nil
	}
	var cleanSkips []string
	for _, r := range skipRoots {
		if r != "" {
			cleanSkips = append(cleanSkips, filepath.Clean(r))
		}
	}
	var searched []string
	for _, dir := range filepath.SplitList(pathEnv) {
		if dir == "" {
			continue
		}
		clean := filepath.Clean(dir)
		if underAny(clean, cleanSkips) {
			continue
		}
		searched = append(searched, clean)
		candidate := filepath.Join(clean, bin)
		if err := executable(candidate); err == nil && canExecute(candidate) {
			return candidate, nil
		}
	}
	if len(searched) == 0 {
		return "", fmt.Errorf("%s: not found (no usable PATH entries outside yolo's own directories)", bin)
	}
	return "", fmt.Errorf("%s: not found in PATH (searched %d directories, skipping yolo's own)",
		bin, len(searched))
}

// underAny reports whether path is one of roots or lives beneath one.
func underAny(path string, roots []string) bool {
	for _, root := range roots {
		if path == root || strings.HasPrefix(path, root+string(filepath.Separator)) {
			return true
		}
	}
	return false
}

// executable reports whether path is an existing regular file with an execute bit.
func executable(path string) error {
	info, err := os.Stat(path)
	if err != nil {
		return err
	}
	if info.IsDir() {
		return fmt.Errorf("%s: is a directory", path)
	}
	if info.Mode()&0o111 == 0 {
		return fmt.Errorf("%s: not executable", path)
	}
	return nil
}

// canExecute reports whether the EFFECTIVE user may execute path — the question the
// kernel answers at exec time, not the one the mode bits answer.
//
// Go's mode-bit check and access(X_OK) disagree exactly when it hurts: a candidate that
// is 0750 root:root passes `Mode()&0o111 != 0` while a non-root effective user cannot run
// it. Returning that candidate made `yolo host -- claude` exit 126 ('permission denied')
// where the shell that launched it had silently skipped to the next PATH entry and
// succeeded — yolo resolving a program the user's own shell resolves fine. Faccessat with
// AT_EACCESS is the effective-uid check exec itself applies, glibc-compatible including
// the root and CAP_DAC_OVERRIDE special cases.
//
// Confirmed LOW by the adversarial review; it ships because yolo's real deployments are
// ROOTLESS (rootless podman), where the disagreeing candidate is an every-day shape.
func canExecute(path string) bool {
	return unix.Faccessat(unix.AT_FDCWD, path, unix.X_OK, unix.AT_EACCESS) == nil
}
