"""Filesystem-state plumbing for shared host directories.

Owns the set-up that happens before any container starts:
  * ensure_global_storage — make sure ~/.local/share/yolo-jail/* and the
    GLOBAL_HOME mountpoints exist (and are the right shape — files vs
    dirs, symlinks for atomic-write paths) so the read-only home mount
    doesn't blow up at runtime.
  * _ensure_symlink — idempotent file→symlink migration.
  * _seed_agent_dir / _migrate_old_overlay / _copy_if_missing — one-time
    copies of auth state into per-workspace overlays.
  * _ac_materialize_under_ws_state — Apple Container workaround for the
    "single-file bind mount shadows parent dir mount" bug.
  * _host_mise_dir — the host-visible mise data dir shared with the jail.
  * _detect_host_timezone, _linux_multilib, _nix_custom_conf_included,
    _detect_nix_daemon_label — pure host-state probes used by run() and
    the check command.
"""

import json
import os
import platform
import shutil
from pathlib import Path
from typing import Optional

from .paths import (
    AGENTS_DIR,
    BUILD_DIR,
    CONTAINER_DIR,
    GLOBAL_CACHE,
    GLOBAL_HOME,
    GLOBAL_MISE,
)


def ensure_global_storage():
    GLOBAL_HOME.mkdir(parents=True, exist_ok=True)
    GLOBAL_MISE.mkdir(parents=True, exist_ok=True)
    GLOBAL_CACHE.mkdir(parents=True, exist_ok=True)
    CONTAINER_DIR.mkdir(parents=True, exist_ok=True)
    AGENTS_DIR.mkdir(parents=True, exist_ok=True)
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    # Pre-create directories and files inside GLOBAL_HOME that will be mountpoints
    # for bind mounts.  GLOBAL_HOME is mounted :ro, so the container runtime cannot
    # create these on the fly — they must already exist in the base filesystem.
    for subdir in [
        ".copilot",
        ".gemini",
        ".claude",
        # Shared credentials dir — all jails mount this rw as a directory so
        # Claude Code's atomic writer (tmp+rename) works.  The old approach
        # used a single-file bind mount which returned EBUSY on rename.
        ".claude-shared-credentials",
        Path(".config") / "git",
        ".npm-global",
        ".local",
        "go",
        ".yolo-shims",
        ".config",
        ".cache",
        ".ssh",
    ]:
        (GLOBAL_HOME / subdir).mkdir(parents=True, exist_ok=True)
    # Migrate credentials from old single-file mount location to new shared dir.
    old_cred = GLOBAL_HOME / ".claude" / ".credentials.json"
    new_cred = GLOBAL_HOME / ".claude-shared-credentials" / ".credentials.json"
    if old_cred.is_file() and not old_cred.is_symlink():
        if not new_cred.exists() or new_cred.stat().st_size == 0:
            try:
                shutil.copy2(old_cred, new_cred)
            except OSError:
                pass
        try:
            old_cred.unlink()
        except OSError:
            pass  # may have restrictive perms — leave for now
    # Ensure the credentials file exists in the shared dir (touch for mountpoint).
    if not new_cred.exists():
        new_cred.touch()
    # File mountpoints — these must exist as files (not dirs) for bind mounts.
    # Only create if missing — existing files from prior runs may have restrictive
    # permissions from container UID mapping; we just need them to exist.
    for fname in [
        ".bash_history",
        ".yolo-bootstrap.sh",
        ".yolo-venv-precreate.sh",
        ".yolo-perf.log",
        ".yolo-socat.log",
        ".yolo-entrypoint.lock",
        # Combined CA bundle: generated by the jail entrypoint at every
        # boot (see entrypoint.generate_ca_bundle).  The jail needs a
        # writable file here because /home/agent is :ro — if we don't
        # bind-mount a writable file over it, the entrypoint's write
        # lands on the read-only layer and errors with EROFS.
        ".yolo-ca-bundle.crt",
        # LSP install sentinel written by ~/.yolo-bootstrap.sh on every
        # boot (records what was installed last time so the next boot
        # can uninstall anything the workspace dropped).  Same EROFS
        # problem as the CA bundle — needs a writable file overlay.
        ".yolo-installed-lsps",
    ]:
        p = GLOBAL_HOME / fname
        if not p.exists():
            p.touch()
    # Files in the :ro /home/agent/ that need atomic writes (lock-file-then-rename)
    # must be symlinks into writable overlay dirs.  Without this, tools like git,
    # Claude Code, and bash fail with EROFS when trying to update these files.
    _ensure_symlink(
        GLOBAL_HOME / ".claude.json",
        Path(".claude") / "claude.json",
    )
    # ~/.gitconfig must also be a symlink — git config uses lock-file-then-rename
    # which fails when the parent dir is :ro.  Point to .config/git/config (the
    # XDG standard location, already inside the writable .config/ overlay).
    _ensure_symlink(
        GLOBAL_HOME / ".gitconfig",
        Path(".config") / "git" / "config",
    )
    # ~/.bashrc — bash doesn't do atomic writes, but some tools that modify it
    # (e.g. mise activate) might.  Symlink into .config/ for safety.
    _ensure_symlink(
        GLOBAL_HOME / ".bashrc",
        Path(".config") / "bashrc",
    )


def _ensure_symlink(link: Path, target: Path):
    """Ensure link is a relative symlink to target, migrating regular files."""
    if link.is_symlink():
        if Path(os.readlink(str(link))) != target:
            link.unlink()
            link.symlink_to(target)
    elif link.exists():
        # Migrate data from old regular file to new target location
        real = link.parent / target
        if not real.exists():
            real.parent.mkdir(parents=True, exist_ok=True)
            try:
                shutil.copy2(link, real)
            except OSError:
                pass  # unreadable (bad perms from prior container run) — skip data
        try:
            link.unlink()
            link.symlink_to(target)
        except OSError:
            pass  # can't replace — leave as-is
    else:
        link.symlink_to(target)


def _host_mise_dir() -> Path:
    """Return the host-visible mise data dir shared with the jail."""
    host_mise_path: str = (
        os.environ.get("YOLO_OUTER_MISE_PATH")
        or os.environ.get("MISE_DATA_DIR")
        or str(Path.home() / ".local" / "share" / "mise")
    )
    host_mise = Path(host_mise_path)
    if not host_mise.exists():
        host_mise.mkdir(parents=True, exist_ok=True)
    return host_mise


def _ac_materialize_under_ws_state(
    src: Path, target_rel: str, ws_state: Path, *, is_dir: bool = False
) -> None:
    """Copy ``src`` into ``ws_state / target_rel`` for Apple Container.

    Apple Container 0.12.3 silently drops the ``-v ws_state:/home/agent``
    parent bind mount as soon as any ``-v host_file:/home/agent/sub/...``
    single-file mount is added (apple/container#1089 — single-file mounts
    use a separate virtiofs share via a hardlink tempdir, and the parent
    dir share gets shadowed).  Nested directory mounts don't trip the
    bug, but single-file mounts do.

    Workaround: instead of bind-mounting, materialize the contents into
    ``ws_state`` directly — the existing ``ws_state:/home/agent`` dir
    mount then exposes them at the expected paths inside the jail.
    """
    dst = ws_state / target_rel
    dst.parent.mkdir(parents=True, exist_ok=True)
    if is_dir:
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(src, dst, symlinks=False)
    else:
        shutil.copy2(src, dst)


def _seed_agent_dir(src: Path, dst: Path, *, skip: tuple[str, ...] = ()):
    """Copy auth-related files from GLOBAL_HOME agent dir into per-workspace overlay.

    Only copies files that don't already exist in dst — the entrypoint regenerates
    configs on every boot, so we only need to seed auth tokens and similar
    persistent state on first use.  Skips subdirectories (those are created by
    the entrypoint as needed).

    ``skip`` lists filenames that are handled via separate shared mounts (e.g.
    .credentials.json) and should not be copied into per-workspace state.
    """
    if not src.is_dir():
        return
    for item in src.iterdir():
        if item.is_file() and item.name not in skip:
            target = dst / item.name
            if not target.exists():
                try:
                    shutil.copy2(item, target)
                except OSError:
                    pass  # permission errors on stale files — skip


# Login-state keys back-propagated from a workspace claude.json into the
# GLOBAL_HOME seed.  Allowlist only — mcpServers, projects, and other
# workspace-specific keys must never leak into the shared seed.
_CLAUDE_JSON_SEED_KEYS = ("oauthAccount", "hasCompletedOnboarding")


def _sync_claude_json_seed(seed: Path, ws: Path) -> None:
    """Two-way sync of Claude login/onboarding state between the GLOBAL_HOME
    seed (``seed``) and a per-workspace overlay's claude.json (``ws``).

    Forward (seed → workspace): merge the seed's keys into the workspace
    file, filling missing keys while preserving workspace-specific config
    (mcpServers, projects, …).  This is how a brand-new workspace boots
    already logged in.

    Reverse (workspace → seed): if the workspace has ``oauthAccount`` and
    the seed lacks it (or doesn't exist), write the allowlisted login keys
    up into the seed, preserving any unrelated keys already there.  Jails
    only write to their per-workspace overlay, so without this the seed
    never comes into existence on installs that first logged in after the
    read-only refactor — and every new workspace boots logged out.

    Never raises: a parse/IO error degrades to a no-op for that direction
    (an unparseable file reads as ``{}``).
    """

    def read_json_dict(path: Path) -> dict:
        try:
            data = json.loads(path.read_text())
        except (OSError, json.JSONDecodeError, ValueError):
            return {}
        return data if isinstance(data, dict) else {}

    seed_data = read_json_dict(seed)
    ws_data = read_json_dict(ws)

    if seed_data:
        merged = False
        for key, val in seed_data.items():
            if key not in ws_data:
                ws_data[key] = val
                merged = True
        if merged:
            try:
                ws.parent.mkdir(parents=True, exist_ok=True)
                ws.write_text(json.dumps(ws_data, indent=2) + "\n")
            except OSError:
                pass

    if ws_data.get("oauthAccount") and not seed_data.get("oauthAccount"):
        for key in _CLAUDE_JSON_SEED_KEYS:
            if key in ws_data:
                seed_data[key] = ws_data[key]
        try:
            seed.parent.mkdir(parents=True, exist_ok=True)
            seed.write_text(json.dumps(seed_data, indent=2) + "\n")
        except OSError:
            pass


def _migrate_old_overlay(old: Path, new: Path):
    """Merge data from a pre-refactor per-workspace overlay dir into the new location.

    Copies files that don't already exist in the target.  Existing files in
    ``new`` are never overwritten so user data created post-refactor wins.
    """
    if not old.is_dir() or not any(old.iterdir()):
        return
    new.mkdir(parents=True, exist_ok=True)
    shutil.copytree(old, new, dirs_exist_ok=True, copy_function=_copy_if_missing)


def _copy_if_missing(src: str, dst: str):
    """shutil copy_function that skips existing files."""
    if not Path(dst).exists():
        shutil.copy2(src, dst)


def _linux_multilib() -> str:
    """Return the Linux multilib directory name for the current architecture.

    The container is always Linux; the arch matches the host (native, not emulated).
    """
    machine = platform.machine()
    _MAP = {
        "x86_64": "x86_64-linux-gnu",
        "aarch64": "aarch64-linux-gnu",
        "arm64": "aarch64-linux-gnu",  # macOS reports arm64
    }
    return _MAP.get(machine, f"{machine}-linux-gnu")


def _nix_custom_conf_included() -> Optional[bool]:
    """Return True if /etc/nix/nix.conf includes /etc/nix/nix.custom.conf.

    Nix reads ``/etc/nix/nix.conf`` (and ``$XDG_CONFIG_HOME/nix/nix.conf``)
    but not arbitrary sibling files.  The Determinate Systems installer
    adds ``!include /etc/nix/nix.custom.conf`` to ``nix.conf`` so the
    "custom" file is actually loaded; the official NixOS installer does
    not.  yolo-jail's macOS setup guide tells users to append settings
    to ``nix.custom.conf``, which silently no-ops on the official
    installer.  This helper lets the ``check`` command explain exactly
    which of the two fixes the user needs.

    Returns True/False if ``/etc/nix/nix.conf`` is readable, None if not
    (e.g. non-macOS host, missing file, permission error).
    """
    conf = Path("/etc/nix/nix.conf")
    if not conf.is_file():
        return None
    try:
        text = conf.read_text()
    except OSError:
        return None
    for raw in text.splitlines():
        stripped = raw.strip()
        if stripped.startswith("#") or not stripped:
            continue
        # Match both ``include`` (fatal if missing) and ``!include``
        # (non-fatal).  Tolerate extra whitespace.
        for prefix in ("!include", "include"):
            if stripped.startswith(prefix):
                rest = stripped[len(prefix) :].lstrip()
                if rest == "/etc/nix/nix.custom.conf":
                    return True
    return False


def _detect_nix_daemon_label() -> Optional[str]:
    """Return the launchd Label of the installed nix-daemon on macOS, or None.

    The Determinate Systems installer registers
    ``systems.determinate.nix-daemon``; the official NixOS installer
    registers ``org.nixos.nix-daemon``.  We look in
    ``/Library/LaunchDaemons/`` for any file whose name ends in
    ``nix-daemon.plist`` and return the stem — launchd labels match the
    plist filename.  First match wins; returns None on non-macOS hosts
    or if no matching plist exists.
    """
    daemon_dir = Path("/Library/LaunchDaemons")
    if not daemon_dir.is_dir():
        return None
    for entry in sorted(daemon_dir.iterdir()):
        if entry.name.endswith("nix-daemon.plist"):
            return entry.stem
    return None


def _detect_host_timezone() -> Optional[str]:
    """Return the host's IANA timezone name (e.g. "America/New_York") or None.

    Passed to the jail container via ``TZ`` env var so `date` and glibc/musl
    time functions inside the jail report the same wall-clock time as the
    host.  Without this, the minimal Linux image defaults to UTC.

    Detection, in order of preference:

      1. ``$TZ`` env var on the host (user explicitly set one — respect it)
      2. ``/etc/timezone`` on Linux — contains the zone name as a plain string
         (``America/New_York\\n``).  Debian/Ubuntu/Arch use this.
      3. ``/etc/localtime`` symlink target — the zone name is the path suffix
         after ``zoneinfo/``.  macOS and some Linux distros (Fedora) use this.

    Returns None if none of these work.  Callers should treat a None return as
    "don't set TZ, leave the container in UTC" rather than failing.
    """
    # 1. Explicit $TZ on host
    tz = os.environ.get("TZ")
    if tz:
        return tz

    # 2. /etc/timezone (plain-text zone name)
    etc_tz = Path("/etc/timezone")
    if etc_tz.is_file():
        try:
            content = etc_tz.read_text().strip()
            if content:
                return content
        except OSError:
            pass

    # 3. /etc/localtime symlink target
    # Typical forms:
    #   /usr/share/zoneinfo/America/New_York     (Linux)
    #   ../usr/share/zoneinfo/America/New_York   (Linux, relative)
    #   /var/db/timezone/zoneinfo/America/New_York (macOS)
    etc_lt = Path("/etc/localtime")
    if etc_lt.is_symlink():
        try:
            target = os.readlink(str(etc_lt))
            marker = "/zoneinfo/"
            idx = target.find(marker)
            if idx >= 0:
                return target[idx + len(marker) :]
        except OSError:
            pass

    return None
