package cli

// packinitplugin_test.go pins the ask that motivated Phase 10: pulling in an existing plugin
// must be TRIVIAL, which operationally means the one command produces a pack that `pack lint`
// accepts. A scaffold that does not lint is not a scaffold, so that is the headline assertion
// here rather than a check on the generated bytes.

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// writeSourcePlugin creates a plugin tree to wrap, under t.TempDir().
func writeSourcePlugin(t *testing.T, name, manifest string) string {
	t.Helper()
	dir := filepath.Join(t.TempDir(), name)
	md := filepath.Join(dir, ".claude-plugin")
	if err := os.MkdirAll(md, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(md, "plugin.json"), []byte(manifest), 0o644); err != nil {
		t.Fatal(err)
	}
	skill := filepath.Join(dir, "skills", "review")
	if err := os.MkdirAll(skill, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(skill, "SKILL.md"),
		[]byte("---\nname: review\ndescription: d\n---\nbody\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	// Content yolo models nothing about — it must travel into the wrapper.
	agents := filepath.Join(dir, "agents")
	if err := os.MkdirAll(agents, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(agents, "reviewer.md"), []byte("# agent\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	return dir
}

// THE acceptance test for the "trivially pull in a plugin" ask: init --from-plugin, then lint,
// with nothing in between.
func TestInitFromPluginProducesALintablePack(t *testing.T) {
	src := writeSourcePlugin(t, "acme-tools",
		`{"name":"acme-tools","description":"acme's tools","skills":["./"]}`)
	packDir := filepath.Join(t.TempDir(), "acme-wrapper")

	var out, errw bytes.Buffer
	if rc := packMain([]string{"init", "--from-plugin", src, packDir},
		&out, &errw, false, nil); rc != 0 {
		t.Fatalf("init --from-plugin rc = %d\nstdout:\n%s\nstderr:\n%s",
			rc, out.String(), errw.String())
	}

	// The plugin's tree came along, manifest and unmodeled content included — the wrapper is
	// what a jail stages and what the host render reads, so anything missing here is missing
	// everywhere.
	for _, rel := range []string{
		"pack.json",
		"skills/acme-tools/.claude-plugin/plugin.json",
		"skills/acme-tools/skills/review/SKILL.md",
		"skills/acme-tools/agents/reviewer.md",
	} {
		if _, err := os.Stat(filepath.Join(packDir, filepath.FromSlash(rel))); err != nil {
			t.Errorf("%s missing from the scaffolded pack: %v", rel, err)
		}
	}

	// THE assertion: lint accepts it. Anything less makes the feature "documented", not
	// "trivial" — which is the whole distinction Phase 10 exists to close.
	var lintOut, lintErr bytes.Buffer
	if rc := packMain([]string{"lint", packDir}, &lintOut, &lintErr, false, nil); rc != 0 {
		t.Fatalf("`pack lint` REJECTED the scaffolded wrapper (rc=%d) — a scaffold that does "+
			"not lint is not a scaffold:\n%s\n%s", rc, lintOut.String(), lintErr.String())
	}

	// The declared tier must be namespaced, or the plugin degrades to loose skills and every
	// non-skill component it ships is refused — the exact thing wrapping it was meant to avoid.
	decl, err := os.ReadFile(filepath.Join(packDir, "pack.json"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(decl), `"tier": "namespaced"`) {
		t.Errorf("the scaffolded pack.json must declare tier namespaced:\n%s", decl)
	}
}

// Re-running is safe: `init` never clobbers, so an author who edited a wrapped file does not lose
// it to a second init. It reports what it left alone rather than staying quiet about it.
func TestInitFromPluginNeverClobbers(t *testing.T) {
	src := writeSourcePlugin(t, "acme-tools", `{"name":"acme-tools","skills":["./"]}`)
	packDir := filepath.Join(t.TempDir(), "wrapper")

	var out, errw bytes.Buffer
	if rc := packMain([]string{"init", "--from-plugin", src, packDir},
		&out, &errw, false, nil); rc != 0 {
		t.Fatalf("first init rc = %d: %s", rc, errw.String())
	}
	edited := filepath.Join(packDir, "skills", "acme-tools", "skills", "review", "SKILL.md")
	if err := os.WriteFile(edited,
		[]byte("---\nname: review\ndescription: d\n---\nMY EDIT\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	var out2, errw2 bytes.Buffer
	if rc := packMain([]string{"init", "--from-plugin", src, packDir},
		&out2, &errw2, false, nil); rc != 0 {
		t.Fatalf("second init rc = %d: %s", rc, errw2.String())
	}
	data, err := os.ReadFile(edited)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "MY EDIT") {
		t.Errorf("re-running init overwrote an edited file: %s", data)
	}
	if !strings.Contains(out2.String(), "skip") {
		t.Errorf("a second init must REPORT what it left alone, not stay quiet:\n%s", out2.String())
	}
}

// A plugin's code-running components are named at init time, with the words that matter. This is
// the moment the user decides whether to trust the tree; deferring it to the next `pack install`
// would put the disclosure after the decision.
func TestInitFromPluginNamesCodeRunningComponents(t *testing.T) {
	src := writeSourcePlugin(t, "acme-tools", `{"name":"acme-tools","skills":["./"],
		"hooks":{"PreToolUse":[]},"mcpServers":{"db":{"command":"x"}},"agents":["./agents"]}`)
	packDir := filepath.Join(t.TempDir(), "wrapper")

	var out, errw bytes.Buffer
	if rc := packMain([]string{"init", "--from-plugin", src, packDir},
		&out, &errw, false, nil); rc != 0 {
		t.Fatalf("rc = %d: %s", rc, errw.String())
	}
	got := out.String()
	for _, want := range []string{"hooks", "mcpServers", "RUNS CODE"} {
		if !strings.Contains(got, want) {
			t.Errorf("init must name %q — a plugin that starts processes must say so at the "+
				"moment the user wraps it:\n%s", want, got)
		}
	}
	// The namespaced invocation is stated, because it is the one fact the filesystem does not
	// show and the user needs to actually call the skills.
	if !strings.Contains(got, "/acme-tools:") {
		t.Errorf("init should state how the plugin's skills invoke:\n%s", got)
	}
}

// A directory that is not a plugin is refused with the file that was looked for. "not a plugin"
// sends someone back to the docs; naming plugin.json sends them to `ls`.
func TestInitFromPluginRefusesNonPlugin(t *testing.T) {
	notAPlugin := t.TempDir()
	var out, errw bytes.Buffer
	if rc := packMain([]string{"init", "--from-plugin", notAPlugin,
		filepath.Join(t.TempDir(), "w")}, &out, &errw, false, nil); rc == 0 {
		t.Fatalf("wrapping a non-plugin dir must fail:\n%s", out.String())
	}
	if !strings.Contains(errw.String(), "plugin.json") {
		t.Errorf("the refusal must name the file it looked for:\n%s", errw.String())
	}
}

// The plain `init` path is untouched by the new flag — the scaffold everyone else gets must not
// have changed shape.
func TestPlainInitStillScaffoldsTheExampleSkill(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "plain-pack")
	var out, errw bytes.Buffer
	if rc := packMain([]string{"init", dir}, &out, &errw, false, nil); rc != 0 {
		t.Fatalf("rc = %d: %s", rc, errw.String())
	}
	for _, rel := range []string{"AGENTS.md", "skills/example/SKILL.md", "README.md"} {
		if _, err := os.Stat(filepath.Join(dir, filepath.FromSlash(rel))); err != nil {
			t.Errorf("%s missing: %v", rel, err)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, "pack.json")); err == nil {
		t.Error("plain init must stay zero-ceremony — no pack.json")
	}
}
