package check

import (
	"bytes"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
	"time"

	"github.com/mschulkind-oss/yolo-jail/internal/containerbuilder"
	"github.com/mschulkind-oss/yolo-jail/internal/nixroots"
	"github.com/mschulkind-oss/yolo-jail/internal/storage"
)

// The extra-platforms footgun WARNING must name this host's own linux double, not a
// hardcoded `aarch64-linux`. The detector matches any `<arch>-linux`, so on an Intel Mac it
// fires for x86_64-linux and used to tell the user to remove a line that is not in their
// nix.conf — a real problem with an unfollowable remedy. BACKLOG E8's bug class, and it
// survived because nothing tested this remedy string at all.
func TestExtraPlatformsRemedyNamesThisHostsSystem(t *testing.T) {
	var out bytes.Buffer
	o := &Options{
		Stdout:      &out,
		IsTTYStdout: func() bool { return false },
		nixHostRoot: t.TempDir(),
	}
	fillDefaults(o)
	o.Exec = func(argv []string, _ string, _ []string, _ time.Duration) ExecResult {
		if slices.Equal(argv, nixCmdArgv("config", "show")) {
			return ExecResult{Ran: true, RC: 0, Stdout: "extra-platforms = x86_64-linux aarch64-linux\n"}
		}
		return ExecResult{Ran: false}
	}
	r := newReporter(&out, false)
	o.nixExtraPlatformsAndBuilder(r)

	want := containerbuilder.BuilderSystem()
	if !strings.Contains(out.String(), "Remove '"+want+"'") {
		t.Errorf("the remedy must name THIS host's linux double (%q), or it asks the user to "+
			"delete a line they do not have:\n%s", want, out.String())
	}
}

const extraPlatformsRow = "extra-platforms includes linux — local Linux builds will be attempted and fail"

// The extra-platforms remedy names this Nix's system file: on Determinate Nix nix.custom.conf, never
// the nix.conf determinate-nixd replaces; on upstream Nix /etc/nix/nix.conf; and where nix-darwin
// generates nix.conf, the configuration's nix.settings.extra-platforms.
func TestExtraPlatformsRemedyNamesThisNixsFile(t *testing.T) {
	const custom, conf = "/etc/nix/nix.custom.conf", "/etc/nix/nix.conf"
	cases := []struct {
		name, version string
		files, links  map[string]string
		want, never   string
	}{
		{"Determinate Nix", determinateNixVersion,
			map[string]string{nixConfFile: determinateManagedNixConf}, nil, custom, conf},
		{"upstream Nix", upstreamNixVersion,
			map[string]string{nixConfFile: officialInstallerNixConf}, nil, conf, custom},
		{"upstream Nix, nix.conf generated by nix-darwin", upstreamNixVersion,
			map[string]string{"nix/store/x-nix.conf": "extra-platforms = aarch64-linux\n"},
			map[string]string{nixConfFile: "nix/store/x-nix.conf"}, "nix.settings.extra-platforms", custom},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			r, out := nixMachine{mac: true, version: tc.version, store: trustedStore,
				config: "extra-platforms = aarch64-linux x86_64-linux\n", files: tc.files, links: tc.links}.nixSection(t)
			f, ok := findingFor(r, extraPlatformsRow)
			if !ok || f.Status != "warn" {
				t.Fatalf("no extra-platforms WARN:\n%s", out)
			}
			if !strings.Contains(f.Note, tc.want) {
				t.Errorf("the remedy must name %s:\n%s", tc.want, f.Note)
			}
			if strings.Contains(f.Note, tc.never) {
				t.Errorf("the remedy names %s, which is not where this Nix takes the setting:\n%s", tc.never, f.Note)
			}
		})
	}
}

// enablesNixCommand reports whether argv turns the `nix-command` experimental
// feature on for itself.
func enablesNixCommand(argv []string) bool {
	i := slices.Index(argv, "--extra-experimental-features")
	return i >= 0 && i+1 < len(argv) && slices.Contains(strings.Fields(argv[i+1]), "nix-command")
}

// officialInstallerNix is an Exec seam behaving like the nix the OFFICIAL
// installer leaves on a Mac: `nix-command` is off, so any `nix <subcommand>`
// that does not turn it on for itself fails with rc 1 and nix's own refusal,
// while `nix --version` (no subcommand) still works. seen records every argv.
func officialInstallerNix(seen *[][]string) func([]string, string, []string, time.Duration) ExecResult {
	return func(argv []string, _ string, _ []string, _ time.Duration) ExecResult {
		*seen = append(*seen, argv)
		if len(argv) == 0 || argv[0] != "nix" {
			return ExecResult{Ran: false}
		}
		if slices.Equal(argv, []string{"nix", "--version"}) {
			return ExecResult{Ran: true, RC: 0, Stdout: "nix (Nix) 2.31.2\n"}
		}
		if !enablesNixCommand(argv) {
			return ExecResult{Ran: true, RC: 1,
				Stderr: "error: experimental Nix feature 'nix-command' is disabled; " +
					"add '--extra-experimental-features nix-command' to enable it\n"}
		}
		switch {
		case slices.Contains(argv, "store") && slices.Contains(argv, "info"):
			return ExecResult{Ran: true, RC: 0,
				Stdout: "Store URL: daemon\nVersion: 2.31.2\nTrusted: 1\n"}
		case slices.Contains(argv, "config") && slices.Contains(argv, "show"):
			return ExecResult{Ran: true, RC: 0, Stdout: "min-free = 1073741824\n"}
		}
		return ExecResult{Ran: false}
	}
}

// TestNixSectionsWorkWithNixCommandOff: on a Mac with the official Nix
// installer, where the `nix-command` feature is OFF by default, the Nix section
// reported "Nix daemon: connection failed" — a false [FAIL] that stopped `yolo
// check` on a working machine — because `nix store info` and `nix config show`
// ran without enabling the feature they live behind.
//
// It drives the SECTIONS (sectionNix on macOS, which reaches the daemon check,
// the extra-platforms probe and hasLinuxBuilder; and sectionAutoGC) through a
// fake nix that refuses any subcommand missing the flag, so reverting any one
// call site to a bare `nix store info` / `nix config show` fails it, as a FAIL
// or as a recorded argv without the flag.
func TestNixSectionsWorkWithNixCommandOff(t *testing.T) {
	var out bytes.Buffer
	var seen [][]string
	o := &Options{IsMacOS: true, Stdout: &out, IsTTYStdout: func() bool { return false },
		nixHostRoot: t.TempDir()}
	fillDefaults(o)
	o.Getenv = func(string) string { return "" } // on the host, wherever the test runs
	o.LookPath = func(name string) (string, bool) { return "/usr/local/bin/" + name, name == "nix" }
	o.Exec = officialInstallerNix(&seen)
	r := newReporter(&out, false)
	o.sectionNix(r)
	o.sectionAutoGC(r)

	if r.failed != 0 {
		t.Errorf("a working nix with nix-command off must not FAIL; got %d:\n%s", r.failed, out.String())
	}
	if !strings.Contains(out.String(), "Nix daemon: connected, user is trusted") {
		t.Errorf("the daemon check did not reach its PASS line:\n%s", out.String())
	}
	var storeInfo, configShow, version int
	for _, argv := range seen {
		if slices.Equal(argv, []string{"nix", "--version"}) {
			version++
			continue
		}
		if !enablesNixCommand(argv) {
			t.Errorf("nix subcommand run without enabling nix-command: %v", argv)
		}
		if slices.Contains(argv, "store") {
			storeInfo++
		}
		if slices.Contains(argv, "config") {
			configShow++
		}
	}
	// Non-vacuous: the daemon check ran once, and `nix config show` ran for the
	// extra-platforms probe, hasLinuxBuilder, and the auto-GC section.
	if storeInfo != 1 || configShow != 3 {
		t.Errorf("expected 1 `store info` and 3 `config show` probes, got %d and %d: %v",
			storeInfo, configShow, seen)
	}
	// Which Nix this is is asked ONCE per check: the auto-GC section reads the answer the Nix
	// section's version row already got.
	if version != 1 {
		t.Errorf("`nix --version` ran %d times across the two sections, want once: %v", version, seen)
	}
}

// TestNixVersionProbeNamesWhatWentWrong: the version probe said "probe failed" for a
// timeout and an exec failure alike, and passed a nix that exited nonzero. Each outcome
// now has its own line, and the probe gets the daemon check's 15 s budget.
func TestNixVersionProbeNamesWhatWentWrong(t *testing.T) {
	cases := []struct {
		name string
		res  ExecResult
		want string
		pass bool
	}{
		{"timeout", ExecResult{Ran: true, Timeout: true}, "did not answer within 15s", false},
		{"not run", ExecResult{Ran: false}, "could not be run: /usr/local/bin/nix", false},
		{"nonzero", ExecResult{Ran: true, RC: 1, Stderr: "boom"}, "`nix --version` exited 1", false},
		{"works", ExecResult{Ran: true, Stdout: "nix (Nix) 2.31.2\n"}, "Nix: 2.31.2", true},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			var out bytes.Buffer
			o := &Options{Stdout: &out, IsTTYStdout: func() bool { return false }}
			fillDefaults(o)
			o.LookPath = func(name string) (string, bool) { return "/usr/local/bin/" + name, name == "nix" }
			var budget time.Duration
			o.Exec = func(argv []string, _ string, _ []string, d time.Duration) ExecResult {
				if slices.Equal(argv, []string{"nix", "--version"}) {
					budget = d
					return tc.res
				}
				return ExecResult{Ran: false}
			}
			r := newReporter(&out, false)
			o.sectionNix(r)
			if !strings.Contains(out.String(), tc.want) {
				t.Errorf("output lacks %q:\n%s", tc.want, out.String())
			}
			if (r.failed == 0) != tc.pass {
				t.Errorf("failed=%d, want pass=%v:\n%s", r.failed, tc.pass, out.String())
			}
			if budget != 15*time.Second {
				t.Errorf("nix --version ran with a %v budget, want 15s", budget)
			}
		})
	}
}

// linuxNix is an Exec seam for a Linux nix whose `nix --version` works and whose
// `nix store info` answers with store. seen records every argv.
func linuxNix(seen *[][]string, store ExecResult) func([]string, string, []string, time.Duration) ExecResult {
	return func(argv []string, _ string, _ []string, _ time.Duration) ExecResult {
		*seen = append(*seen, argv)
		switch {
		case slices.Equal(argv, []string{"nix", "--version"}):
			return ExecResult{Ran: true, RC: 0, Stdout: "nix (Nix) 2.31.2\n"}
		case slices.Equal(argv, nixCmdArgv("store", "info")):
			return store
		}
		return ExecResult{Ran: false}
	}
}

// runLinuxNixSection drives sectionNix as a Linux host with nix on the PATH, and systemctl on it
// too when systemctl is true. A HOST, whatever runs the test: the environment is empty rather than
// inherited, since a YOLO_VERSION would make it a jail, and one with no nix daemon is not probed.
func runLinuxNixSection(t *testing.T, store ExecResult, systemctl bool) (*reporter, [][]string, string) {
	t.Helper()
	var out bytes.Buffer
	var seen [][]string
	o := &Options{IsMacOS: false, Stdout: &out, IsTTYStdout: func() bool { return false }}
	fillDefaults(o)
	o.Getenv = func(string) string { return "" }
	o.LookPath = func(name string) (string, bool) {
		return "/usr/bin/" + name, name == "nix" || (systemctl && name == "systemctl")
	}
	o.Exec = linuxNix(&seen, store)
	r := newReporter(&out, false)
	o.sectionNix(r)
	return r, seen, out.String()
}

// findingFor returns the recorded finding whose message is msg.
func findingFor(r *reporter, msg string) (Finding, bool) {
	for _, f := range r.findings {
		if f.Message == msg {
			return f, true
		}
	}
	return Finding{}, false
}

// PS-D5 (docs/design/provisioner-sets.md): the daemon connectivity probe runs on every OS where
// nix is found. It was gated on macOS, so a Linux host whose daemon was down got no line at all
// before the launch that builds its image through that daemon. The trusted-user verdict and the
// extra-platforms and builder block stay macOS-only: a Linux daemon answering "Trusted: 0" is
// connected, and no `nix config show` is asked for.
func TestTheNixDaemonProbeRunsOffMacOS(t *testing.T) {
	r, seen, out := runLinuxNixSection(t, ExecResult{Ran: true, RC: 0,
		Stdout: "Store URL: daemon\nVersion: 2.31.2\nTrusted: 0\n"}, true)
	if f, ok := findingFor(r, "Nix daemon: connected"); !ok || f.Status != "pass" {
		t.Errorf("a Linux host with a working daemon must get the connected PASS line:\n%s", out)
	}
	if strings.Contains(out, "NOT trusted") {
		t.Errorf("the trusted-user verdict is macOS-only (it diagnoses the builder offload):\n%s", out)
	}
	var storeInfo int
	for _, argv := range seen {
		if slices.Equal(argv, nixCmdArgv("store", "info")) {
			storeInfo++
		}
		if slices.Contains(argv, "config") {
			t.Errorf("the extra-platforms and builder block must stay macOS-only, but ran %v", argv)
		}
	}
	if storeInfo != 1 {
		t.Errorf("`nix store info` ran %d times on Linux, want once: %v", storeInfo, seen)
	}
}

// PS-D5's remedy half: off macOS the timeout and the failure each name the restart for the
// host's service manager, systemd's where systemctl is on the PATH and a sentence naming the
// service where it is not (a jail, whose daemon is the host's).
func TestTheLinuxNixDaemonFaultsNameTheRestart(t *testing.T) {
	const systemd = "sudo systemctl restart nix-daemon"
	const hung = "Nix daemon: store operation timed out (daemon may be hung)"
	cases := []struct {
		name      string
		store     ExecResult
		systemctl bool
		msg, want string
	}{
		{"timeout, systemd", ExecResult{Ran: true, Timeout: true}, true, hung, systemd},
		{"timeout, no systemctl", ExecResult{Ran: true, Timeout: true}, false, hung,
			"there is no systemctl here"},
		{"refused, systemd", ExecResult{Ran: true, RC: 1, Stderr: "error: cannot connect to socket at " +
			"'/nix/var/nix/daemon-socket/socket': Connection refused\n"},
			true, "Nix daemon: connection failed", "Connection refused — Restart the Nix daemon: " + systemd},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			r, _, out := runLinuxNixSection(t, tc.store, tc.systemctl)
			f, ok := findingFor(r, tc.msg)
			if !ok {
				t.Fatalf("no %q finding:\n%s", tc.msg, out)
			}
			if f.Status != "fail" {
				t.Errorf("%q graded %s, want fail", tc.msg, f.Status)
			}
			if !strings.Contains(f.Note, tc.want) {
				t.Errorf("the remedy lacks %q: %q", tc.want, f.Note)
			}
			if strings.Contains(f.Note, "launchctl") {
				t.Errorf("a Linux remedy names launchd: %q", f.Note)
			}
		})
	}
}

// A STORE OPENED DIRECTLY IS NOT A DAEMON THAT ANSWERED. `nix store info` succeeds on a
// single-user install, and for root on any install, by opening the store itself ("Store URL:
// local"), so no daemon was asked at all. Off macOS that used to read "Nix daemon: connected",
// a claim about a daemon that may not exist, on a host whose jails then get no daemon socket to
// delegate to (internal/cli/run's shouldMountHostNix). The line says what was found instead.
func TestALocalNixStoreIsNotReportedAsAConnectedDaemon(t *testing.T) {
	r, _, out := runLinuxNixSection(t, ExecResult{Ran: true, RC: 0,
		Stdout: "Store URL: local\nVersion: 2.31.2\nTrusted: 1\n"}, true)
	if _, ok := findingFor(r, "Nix daemon: connected"); ok {
		t.Errorf("a store nix opened directly must not be reported as a connected daemon:\n%s", out)
	}
	f, ok := findingFor(r, "Nix store: local, opened directly (no daemon was asked)")
	if !ok || f.Status != "pass" {
		t.Errorf("the local store must be named as what answered:\n%s", out)
	}
	// And a daemon reached by its socket's URL is still a daemon.
	r, _, out = runLinuxNixSection(t, ExecResult{Ran: true, RC: 0,
		Stdout: "Store URL: unix:///nix/var/nix/daemon-socket/socket\nVersion: 2.31.2\n"}, true)
	if _, ok := findingFor(r, "Nix daemon: connected"); !ok {
		t.Errorf("a daemon reached by its socket URL is a connected daemon:\n%s", out)
	}
}

// A JAIL WHOSE LAUNCH GAVE IT NO NIX DAEMON HAS NO BROKEN DAEMON. The launcher gives a container
// jail the host's nix daemon by binding the host's daemon-socket directory and setting
// NIX_REMOTE=daemon, together, and gives neither on a Mac whose store holds darwin paths, on Apple
// Container, on a Linux host running no daemon, or for a sealed launch. There `nix store info` is
// answered by nix opening the --read-only jail's store as root, which fails, and the Nix section
// read that as "Nix daemon: connection failed" with a restart for a daemon that does not exist:
// measured on the 2026-10-01 and 2026-10-02 macOS podman nightlies, where it failed
// TestYoloCheckAvailableInsideJail with exactly the stderr below. It is a [SKIP] saying what nix
// here can and cannot do, never a [FAIL], and the restart is named nowhere.
//
// The guard half: a jail whose launch DID give it a daemon (NIX_REMOTE=daemon) still fails on a
// daemon that went away, socket and all, and a host and a macos-user jail, whose nix is the host's,
// are probed as before.
func TestAJailTheLaunchGaveNoNixDaemonIsNotABrokenDaemon(t *testing.T) {
	const restart = "Restart the nix-daemon service"
	remount := ExecResult{Ran: true, RC: 1, Stderr: "error: remounting \"/nix/store\" writable: Invalid argument\n"}
	refused := ExecResult{Ran: true, RC: 1, Stderr: "error: cannot connect to socket at " +
		"'/nix/var/nix/daemon-socket/socket': No such file or directory\n"}
	run := func(t *testing.T, mac, inJail bool, env map[string]string, socket bool, store ExecResult) (*reporter, [][]string, string) {
		t.Helper()
		var out bytes.Buffer
		o := nixMachine{mac: mac, version: upstreamNixVersion, store: store,
			files: map[string]string{upstreamPlist: ""}}.options(t, &out)
		o.Getenv = func(k string) string {
			if k == "YOLO_VERSION" && inJail {
				return "9.9.9-test"
			}
			return env[k]
		}
		o.PathExists = func(p string) bool { return socket && p == nixroots.DefaultSocket }
		o.LookPath = func(name string) (string, bool) { return "/usr/bin/" + name, name == "nix" }
		var seen [][]string
		exec := o.Exec
		o.Exec = func(argv []string, dir string, env []string, d time.Duration) ExecResult {
			seen = append(seen, argv)
			return exec(argv, dir, env, d)
		}
		r := newReporter(&out, false)
		o.sectionNix(r)
		return r, seen, out.String()
	}

	t.Run("container jail, no daemon mounted", func(t *testing.T) {
		r, seen, out := run(t, false, true, nil, false, remount)
		if r.failed != 0 {
			t.Errorf("a jail its launch gave no nix daemon is not a broken daemon, but got %d [FAIL]:\n%s", r.failed, out)
		}
		if strings.Contains(out, restart) || strings.Contains(out, "systemctl") {
			t.Errorf("no daemon exists here to restart:\n%s", out)
		}
		var skip *Finding
		for i, f := range r.findings {
			if f.Status == "skip" && strings.HasPrefix(f.Message, "Nix daemon:") {
				skip = &r.findings[i]
			}
		}
		if skip == nil {
			t.Fatalf("no [SKIP] saying this jail has no nix daemon:\n%s", out)
		}
		for _, want := range []string{"read-only store", "`nix config show` works", "`nix build`",
			"YOLO_NIX_HOST_DAEMON=1", "YOLO_NIX_HOST_STORE_LINUX=1", "build jail excepted",
			"run `yolo check` on the host", "relaunch the jail"} {
			if !strings.Contains(skip.Note, want) {
				t.Errorf("the [SKIP]'s note lacks %q:\n%s", want, skip.Note)
			}
		}
		for _, argv := range seen {
			if slices.Equal(argv, nixCmdArgv("store", "info")) {
				t.Errorf("`nix store info` ran with no daemon to ask; its answer is the jail's own read-only store")
			}
		}
	})

	t.Run("container jail, mounted daemon gone", func(t *testing.T) {
		r, _, out := run(t, false, true, map[string]string{"NIX_REMOTE": "daemon"}, false, refused)
		f, ok := findingFor(r, "Nix daemon: connection failed")
		if !ok || f.Status != "fail" {
			t.Fatalf("a daemon the launch mounted and that is gone is a real fault:\n%s", out)
		}
		if !strings.Contains(f.Note, "No such file or directory") || !strings.Contains(f.Note, restart) {
			t.Errorf("the fault must keep nix's line and name the host's restart:\n%s", f.Note)
		}
	})

	connected := ExecResult{Ran: true, RC: 0, Stdout: "Store URL: daemon\nVersion: 2.34.7\nTrusted: 0\n"}
	t.Run("container jail, daemon mounted", func(t *testing.T) {
		r, _, out := run(t, false, true, map[string]string{"NIX_REMOTE": "daemon"}, true, connected)
		if f, ok := findingFor(r, "Nix daemon: connected"); !ok || f.Status != "pass" {
			t.Errorf("a jail with the host's daemon mounted is probed as before:\n%s", out)
		}
	})

	// The socket alone counts: nix's own `auto` store reaches a daemon through it.
	t.Run("container jail, socket without NIX_REMOTE", func(t *testing.T) {
		r, _, out := run(t, false, true, nil, true, connected)
		if f, ok := findingFor(r, "Nix daemon: connected"); !ok || f.Status != "pass" {
			t.Errorf("a jail with the host's daemon socket is probed:\n%s", out)
		}
	})

	t.Run("linux host, no socket", func(t *testing.T) {
		r, _, out := run(t, false, false, nil, false, remount)
		if f, ok := findingFor(r, "Nix daemon: connection failed"); !ok || f.Status != "fail" {
			t.Errorf("a host is probed whatever its socket says:\n%s", out)
		}
	})

	t.Run("macos-user jail, no socket", func(t *testing.T) {
		r, _, out := run(t, true, true, nil, false, refused)
		if f, ok := findingFor(r, "Nix daemon: connection failed"); !ok || f.Status != "fail" {
			t.Errorf("a macos-user jail runs the host's nix against the host's daemon, so it is probed:\n%s", out)
		}
	})
}

// The no-daemon [SKIP] names the launcher's two macOS dials, a second spelling of names the run
// pipeline owns (check does not import it). A renamed dial would leave the note naming a variable
// nothing reads, so the launcher's source must still spell both.
func TestTheNoDaemonNoteNamesTheLaunchersDials(t *testing.T) {
	src, err := os.ReadFile(filepath.Join("..", "run", "hostprobes.go"))
	must(t, err)
	for _, dial := range []string{`"YOLO_NIX_HOST_DAEMON"`, `"YOLO_NIX_HOST_STORE_LINUX"`} {
		if !strings.Contains(string(src), dial) {
			t.Errorf("internal/cli/run/hostprobes.go no longer spells %s, which jailNoNixDaemonNote names", dial)
		}
		if !strings.Contains(jailNoNixDaemonNote, strings.Trim(dial, `"`)+"=1") {
			t.Errorf("jailNoNixDaemonNote does not name %s", dial)
		}
	}
}

// What the two Nix distributions leave on a machine, as far as the Nix sections' hints care.
// The `--version` lines are nix-src src/libmain/shared.cc's, and the nix.conf bodies are what
// each installer writes.
const (
	determinateNixVersion = "nix (Determinate Nix 3.22.5) 2.35.2\n"
	upstreamNixVersion    = "nix (Nix) 2.34.7\n"
	lixNixVersion         = "nix (Lix, like Nix) 2.91.1\n"

	// determinate-nixd's own nix.conf, which it replaces; user settings go in nix.custom.conf.
	determinateManagedNixConf = "# DETERMINATE NIX CONFIG\n# do not modify! this file will be replaced!\n\n" +
		"!include nix.custom.conf\n"
	// The Determinate installer's, installing upstream Nix.
	determinateInstallerNixConf = "# Generated by https://github.com/DeterminateSystems/nix-installer.\n\n" +
		"build-users-group = nixbld\nextra-experimental-features = nix-command flakes\n!include nix.custom.conf\n"
	// The official nixos.org script's: no include at all.
	officialInstallerNixConf = "build-users-group = nixbld\n"

	// Host-root-relative paths of the files the hints read.
	nixConfFile      = "etc/nix/nix.conf"
	upstreamPlist    = "Library/LaunchDaemons/org.nixos.nix-daemon.plist"
	determinatePlist = "Library/LaunchDaemons/systems.determinate.nix-daemon.plist"
	nixHookPlist     = "Library/LaunchDaemons/systems.determinate.nix-installer.nix-hook.plist"
)

var (
	trustedStore   = ExecResult{Ran: true, RC: 0, Stdout: "Store URL: daemon\nVersion: 2.35.2\nTrusted: 1\n"}
	untrustedStore = ExecResult{Ran: true, RC: 0, Stdout: "Store URL: daemon\nVersion: 2.35.2\nTrusted: 0\n"}
)

// nixMachine is a fake host for the Nix sections: what `nix --version`, `nix store info` and
// `nix config show` answer, and the files under the host root the sections read /etc/nix and
// /Library/LaunchDaemons from (root-relative path → content). Off macOS it has systemctl.
type nixMachine struct {
	mac, inJail bool
	version     string
	store       ExecResult
	config      string
	files       map[string]string
	// links are symbolic links under the host root (root-relative path → root-relative target),
	// made after files: a nix-darwin or NixOS /etc/nix/nix.conf is one into the Nix store.
	links map[string]string
	// user is the account check runs as, testUser when "".
	user string
}

// testUser is the account a nixMachine's check runs as unless it names another.
const testUser = "alice"

func (m nixMachine) options(t *testing.T, out *bytes.Buffer) *Options {
	t.Helper()
	// Resolved where it is minted: on macOS t.TempDir() is under /var/folders, a symlink to
	// /private/var/folders, and the generated-nix.conf probe compares resolved paths.
	root, err := filepath.EvalSymlinks(t.TempDir())
	must(t, err)
	for rel, body := range m.files {
		p := filepath.Join(root, rel)
		must(t, os.MkdirAll(filepath.Dir(p), 0o755))
		must(t, os.WriteFile(p, []byte(body), 0o644))
	}
	for rel, target := range m.links {
		p := filepath.Join(root, rel)
		must(t, os.MkdirAll(filepath.Dir(p), 0o755))
		must(t, os.Symlink(filepath.Join(root, target), p))
	}
	o := &Options{IsMacOS: m.mac, Stdout: out, IsTTYStdout: func() bool { return false }, nixHostRoot: root}
	fillDefaults(o)
	o.currentUser = func() string {
		if m.user != "" {
			return m.user
		}
		return testUser
	}
	o.Getenv = func(k string) string {
		if k == "YOLO_VERSION" && m.inJail {
			return "9.9.9-test"
		}
		return ""
	}
	o.LookPath = func(name string) (string, bool) {
		return "/usr/bin/" + name, name == "nix" || (!m.mac && name == "systemctl")
	}
	o.Exec = func(argv []string, _ string, _ []string, _ time.Duration) ExecResult {
		switch {
		case slices.Equal(argv, []string{"nix", "--version"}):
			return ExecResult{Ran: true, RC: 0, Stdout: m.version}
		case slices.Equal(argv, nixCmdArgv("store", "info")):
			return m.store
		case slices.Equal(argv, nixCmdArgv("config", "show")):
			return ExecResult{Ran: true, RC: 0, Stdout: m.config}
		}
		return ExecResult{Ran: false}
	}
	return o
}

// nixSection runs the Nix section on m.
func (m nixMachine) nixSection(t *testing.T) (*reporter, string) {
	t.Helper()
	var out bytes.Buffer
	o := m.options(t, &out)
	r := newReporter(&out, false)
	o.sectionNix(r)
	return r, out.String()
}

// Which Nix this is is asked ONCE per check. Here every reader of it runs: the version row, the
// untrusted hint's file and restart, and the auto-GC section's verdict on a min-free of 0.
func TestWhichNixIsAskedOncePerCheck(t *testing.T) {
	var out bytes.Buffer
	o := nixMachine{mac: true, version: determinateNixVersion, store: untrustedStore,
		config: "min-free = 0\n"}.options(t, &out)
	exec, versions := o.Exec, 0
	o.Exec = func(argv []string, dir string, env []string, d time.Duration) ExecResult {
		if slices.Equal(argv, []string{"nix", "--version"}) {
			versions++
		}
		return exec(argv, dir, env, d)
	}
	r := newReporter(&out, false)
	o.sectionNix(r)
	o.sectionAutoGC(r)
	if !strings.Contains(out.String(), "nix.custom.conf") || !strings.Contains(out.String(), "determinate-nixd") {
		t.Fatalf("the hints did not read the distribution:\n%s", out.String())
	}
	if versions != 1 {
		t.Errorf("`nix --version` ran %d times in one check, want once", versions)
	}
}

// The version row names the distribution instead of echoing `nix --version`: Determinate Nix's
// own version with the Nix it is built from, upstream's version, and an unrecognized Nix verbatim.
func TestTheNixVersionRowNamesTheDistribution(t *testing.T) {
	for version, want := range map[string]string{
		determinateNixVersion: "Nix: Determinate Nix 3.22.5 (based on Nix 2.35.2)",
		upstreamNixVersion:    "Nix: 2.34.7",
		lixNixVersion:         "Nix: nix (Lix, like Nix) 2.91.1",
	} {
		r, out := nixMachine{version: version, store: trustedStore}.nixSection(t)
		if f, ok := findingFor(r, want); !ok || f.Status != "pass" {
			t.Errorf("no %q PASS row:\n%s", want, out)
		}
	}
}

// The untrusted-user hint is the one fix for THIS install, as a command to paste: the file a
// trusted-users line takes effect in, and the restart for the daemon this Nix runs. Determinate
// Nix replaces /etc/nix/nix.conf, so it is never named there; upstream Nix takes the line in
// nix.custom.conf only when nix.conf includes that file and does not set trusted-users again
// after the include (the last assignment wins), and in nix.conf itself otherwise. Nothing asks
// for an include line to be appended any more: on upstream Nix, appending to nix.conf works alone.
//
// THE LINE ADDS, IT NEVER ASSIGNS. A `trusted-users = …` line is an assignment and replaces the
// list: measured with nix 2.34.8, `trusted-users = root alice` then an appended
// `trusted-users = root bob` trusts `root bob`, so alice is dropped. That is the runbook's own
// machine (mac-sandvault-session.md §5, the "sets trusted-users after the include" case below),
// where the hint told sandvault-matt to append a line that untrusted matt. `extra-trusted-users`
// appends to the list (measured: `root alice bob`).
func TestTheUntrustedHintNamesThisNixsFileAndRestart(t *testing.T) {
	const custom, conf = "/etc/nix/nix.custom.conf", "/etc/nix/nix.conf"
	const trustCmd = `echo "extra-trusted-users = ` + testUser + `" | sudo tee -a `
	cases := []struct {
		name, version string
		files         map[string]string
		file, label   string
	}{
		{"Determinate Nix, the upstream daemon's plist left behind", determinateNixVersion,
			map[string]string{nixConfFile: determinateManagedNixConf, upstreamPlist: "", determinatePlist: "",
				nixHookPlist: ""},
			custom, storage.DeterminateNixDaemonLabel},
		{"Determinate Nix, nothing readable", determinateNixVersion, nil,
			custom, storage.DeterminateNixDaemonLabel},
		{"upstream Nix from the Determinate installer", upstreamNixVersion,
			map[string]string{nixConfFile: determinateInstallerNixConf, upstreamPlist: "", nixHookPlist: ""},
			custom, storage.UpstreamNixDaemonLabel},
		{"upstream Nix from the official installer", upstreamNixVersion,
			map[string]string{nixConfFile: officialInstallerNixConf, upstreamPlist: ""},
			conf, storage.UpstreamNixDaemonLabel},
		{"upstream Nix whose nix.conf sets trusted-users after the include", upstreamNixVersion,
			map[string]string{nixConfFile: "!include /etc/nix/nix.custom.conf\ntrusted-users = root matt\n",
				upstreamPlist: ""},
			conf, storage.UpstreamNixDaemonLabel},
		{"upstream Nix, the Determinate daemon's plist left behind", upstreamNixVersion,
			map[string]string{nixConfFile: officialInstallerNixConf, upstreamPlist: "", determinatePlist: ""},
			conf, storage.UpstreamNixDaemonLabel},
		{"upstream Nix, nothing readable", upstreamNixVersion, nil,
			conf, storage.UpstreamNixDaemonLabel},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			r, out := nixMachine{mac: true, version: tc.version, store: untrustedStore, files: tc.files}.nixSection(t)
			f, ok := findingFor(r, "Nix daemon: connected but user is NOT trusted")
			if !ok || f.Status != "warn" {
				t.Fatalf("no untrusted WARN:\n%s", out)
			}
			if !strings.Contains(f.Note, trustCmd+tc.file) {
				t.Errorf("the hint must say `%s%s`:\n%s", trustCmd, tc.file, f.Note)
			}
			if !strings.Contains(f.Note, "sudo launchctl kickstart -k system/"+tc.label) {
				t.Errorf("the hint must restart system/%s:\n%s", tc.label, f.Note)
			}
			if strings.Contains(f.Note, `"trusted-users =`) {
				t.Errorf("a `trusted-users =` line replaces the list and drops whoever is on it:\n%s", f.Note)
			}
			if strings.Contains(f.Note, "!include") {
				t.Errorf("the hint must not ask for an include line:\n%s", f.Note)
			}
			if tc.file == conf && strings.Contains(f.Note, "nix.custom.conf") {
				t.Errorf("a line in nix.custom.conf would not take effect here:\n%s", f.Note)
			}
			if tc.version == determinateNixVersion && strings.Contains(f.Note, conf) {
				t.Errorf("a Determinate Nix user must never be sent to the nix.conf it replaces:\n%s", f.Note)
			}
		})
	}
}

// The hint names the account check runs as, not `$(whoami)`, which expands in whatever shell the
// human pastes it into. On the macos-user backend check runs inside the sandbox as the dedicated
// macOS account, which has no sudo, so the human pastes the command in their own terminal and
// `$(whoami)` added their own, already trusted, user: the warning never cleared.
func TestTheUntrustedHintNamesTheAccountCheckRunsAs(t *testing.T) {
	r, out := nixMachine{mac: true, inJail: true, user: "sandbox-acct", version: upstreamNixVersion,
		store: untrustedStore, files: map[string]string{nixConfFile: officialInstallerNixConf, upstreamPlist: ""}}.nixSection(t)
	f, ok := findingFor(r, "Nix daemon: connected but user is NOT trusted")
	if !ok {
		t.Fatalf("no untrusted WARN:\n%s", out)
	}
	if !strings.Contains(f.Note, `echo "extra-trusted-users = sandbox-acct" | sudo tee -a /etc/nix/nix.conf`) {
		t.Errorf("the hint must add the account check runs as:\n%s", f.Note)
	}
	if strings.Contains(f.Note, "whoami") {
		t.Errorf("`$(whoami)` names whoever pastes the command, not the account the daemon refused:\n%s", f.Note)
	}
}

// A nix-darwin or NixOS /etc/nix/nix.conf is generated from the system configuration: a symlink
// into the Nix store (/etc/nix/nix.conf -> /etc/static/nix/nix.conf -> /nix/store/…-nix.conf) with
// no include. A line appended there fails on the read-only store or is discarded by the next
// rebuild, so the fix is the configuration's nix.settings, and no hint says `tee -a` there. A
// nix.conf linked anywhere else (a dotfiles checkout) still takes the appended line.
func TestTheHintsOnAGeneratedNixConfSetTheConfiguration(t *testing.T) {
	generated := map[string]string{nixConfFile: "etc/static/nix/nix.conf", "etc/static/nix/nix.conf": "nix/store/x-nix.conf"}
	storeConf := map[string]string{"nix/store/x-nix.conf": "trusted-users = root matt\n", upstreamPlist: ""}

	r, out := nixMachine{mac: true, version: upstreamNixVersion, store: untrustedStore,
		files: storeConf, links: generated}.nixSection(t)
	f, ok := findingFor(r, "Nix daemon: connected but user is NOT trusted")
	if !ok {
		t.Fatalf("no untrusted WARN:\n%s", out)
	}
	for _, want := range []string{"nix.settings.trusted-users", "rebuild", testUser,
		"sudo launchctl kickstart -k system/" + storage.UpstreamNixDaemonLabel} {
		if !strings.Contains(f.Note, want) {
			t.Errorf("the trust hint on a generated nix.conf lacks %q:\n%s", want, f.Note)
		}
	}
	if strings.Contains(f.Note, "tee -a") {
		t.Errorf("a line appended to a generated nix.conf does not last:\n%s", f.Note)
	}

	r, out = nixMachine{version: upstreamNixVersion, config: "min-free = 0\n",
		files: storeConf, links: generated}.autoGCSection(t)
	f, ok = findingFor(r, minFreeOffRow)
	if !ok {
		t.Fatalf("no min-free WARN:\n%s", out)
	}
	for _, want := range []string{"nix.settings.min-free", "nix.settings.max-free", "rebuild"} {
		if !strings.Contains(f.Note, want) {
			t.Errorf("the auto-GC remedy on a generated nix.conf lacks %q:\n%s", want, f.Note)
		}
	}
	if strings.Contains(f.Note, "Add to /etc/nix") {
		t.Errorf("a line added to a generated nix.conf does not last:\n%s", f.Note)
	}

	// Linked, but not into the store: the file the link names takes the line.
	r, out = nixMachine{mac: true, version: upstreamNixVersion, store: untrustedStore,
		files: map[string]string{"home/matt/dotfiles/nix.conf": officialInstallerNixConf, upstreamPlist: ""},
		links: map[string]string{nixConfFile: "home/matt/dotfiles/nix.conf"}}.nixSection(t)
	f, ok = findingFor(r, "Nix daemon: connected but user is NOT trusted")
	if !ok {
		t.Fatalf("no untrusted WARN:\n%s", out)
	}
	if !strings.Contains(f.Note, "sudo tee -a /etc/nix/nix.conf") || strings.Contains(f.Note, "nix.settings") {
		t.Errorf("a nix.conf linked outside the store takes an appended line:\n%s", f.Note)
	}
}

// A Nix the section does not recognize, with no daemon plist to read, still gets a command and
// says where its label is found.
func TestTheUntrustedHintOnAnUnrecognizedNixSaysWhereTheLabelIs(t *testing.T) {
	r, out := nixMachine{mac: true, version: lixNixVersion, store: untrustedStore,
		files: map[string]string{nixConfFile: officialInstallerNixConf}}.nixSection(t)
	f, ok := findingFor(r, "Nix daemon: connected but user is NOT trusted")
	if !ok {
		t.Fatalf("no untrusted WARN:\n%s", out)
	}
	for _, want := range []string{`sudo tee -a /etc/nix/nix.conf`, "system/<label>", "/Library/LaunchDaemons"} {
		if !strings.Contains(f.Note, want) {
			t.Errorf("the hint lacks %q:\n%s", want, f.Note)
		}
	}
}

// A hung daemon on a Mac: the restart names the daemon this Nix runs, and determinate-nixd is
// named only on Determinate Nix, whose daemon it is.
func TestTheMacNixDaemonTimeoutNamesTheDaemonItIs(t *testing.T) {
	const hung = "Nix daemon: store operation timed out (daemon may be hung)"
	bothPlists := map[string]string{upstreamPlist: "", determinatePlist: ""}

	r, out := nixMachine{mac: true, version: determinateNixVersion, store: ExecResult{Ran: true, Timeout: true},
		files: bothPlists}.nixSection(t)
	f, ok := findingFor(r, hung)
	if !ok || f.Status != "fail" {
		t.Fatalf("no timeout FAIL:\n%s", out)
	}
	if want := "sudo launchctl kickstart -k system/" + storage.DeterminateNixDaemonLabel; !strings.Contains(f.Note, want) {
		t.Errorf("the Determinate Nix remedy lacks %q:\n%s", want, f.Note)
	}
	// The guide no longer covers Determinate Nix, so a pointer into it is a dead end.
	if strings.Contains(f.Note, "userguide/") {
		t.Errorf("the Determinate Nix remedy points into the guide, which no longer covers it:\n%s", f.Note)
	}

	r, out = nixMachine{mac: true, version: upstreamNixVersion, store: ExecResult{Ran: true, Timeout: true},
		files: map[string]string{upstreamPlist: ""}}.nixSection(t)
	f, ok = findingFor(r, hung)
	if !ok || f.Status != "fail" {
		t.Fatalf("no timeout FAIL:\n%s", out)
	}
	if !strings.Contains(f.Note, "sudo launchctl kickstart -k system/"+storage.UpstreamNixDaemonLabel) {
		t.Errorf("the upstream Nix remedy must restart its own daemon:\n%s", f.Note)
	}
	if strings.Contains(strings.ToLower(f.Note), "determinate") {
		t.Errorf("an upstream Nix user has no determinate-nixd:\n%s", f.Note)
	}
}

// A refused connection on a Mac was a dead end, nix's first stderr line and nothing else. It now
// carries the restart for this Nix's daemon, as the Linux branch does.
func TestTheMacNixDaemonConnectionFailureNamesTheRestart(t *testing.T) {
	refused := ExecResult{Ran: true, RC: 1, Stderr: "error: cannot connect to socket at " +
		"'/nix/var/nix/daemon-socket/socket': Connection refused\n"}
	for version, label := range map[string]string{
		determinateNixVersion: storage.DeterminateNixDaemonLabel,
		upstreamNixVersion:    storage.UpstreamNixDaemonLabel,
	} {
		r, out := nixMachine{mac: true, version: version, store: refused,
			files: map[string]string{upstreamPlist: "", determinatePlist: ""}}.nixSection(t)
		f, ok := findingFor(r, "Nix daemon: connection failed")
		if !ok || f.Status != "fail" {
			t.Fatalf("no connection FAIL:\n%s", out)
		}
		if !strings.Contains(f.Note, "Connection refused") ||
			!strings.Contains(f.Note, "sudo launchctl kickstart -k system/"+label) {
			t.Errorf("%s: the remedy must keep nix's line and restart system/%s:\n%s", version, label, f.Note)
		}
	}
}
