package entrypoint

// floorlaunchers_test.go covers AR-L5 (docs/reference/agent-program-runtimes.md): a launcher whose
// declared Node floor nothing met at generation is regenerated by the provisioning stage once the
// floor is met, so the launch that installed the interpreter already runs its program under it.

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mschulkind-oss/yolo-jail/internal/packload"
	"github.com/mschulkind-oss/yolo-jail/internal/shquote"
)

// floorLauncherHome is a jail home whose staged packs declare one npm program with floor, with
// the image's node too old and an empty mise store, so generation resolves no interpreter.
func floorLauncherHome(t *testing.T, bin, floor string) (*Env, string) {
	t.Helper()
	t.Cleanup(packload.OverrideSkewTolerance(false))
	stubImageNode(t, "20.20.2")
	store := fakeMiseStore(t)
	home := t.TempDir()
	e := NewEnv(map[string]string{
		"JAIL_HOME":      home,
		"YOLO_WORKSPACE": filepath.Join(home, "ws"),
		"YOLO_PACK_ROOT": stageFloorPacks(t, map[string]string{"floorpack": floorProgram(bin, floor)}),
	})
	return e, store
}

// installFakeNode puts a runnable node at <store>/<version>/bin/node, as `mise install` would.
func installFakeNode(t *testing.T, store, version string) string {
	t.Helper()
	bin := filepath.Join(store, version, "bin")
	if err := os.MkdirAll(bin, 0o755); err != nil {
		t.Fatal(err)
	}
	node := filepath.Join(bin, "node")
	if err := os.WriteFile(node, []byte("#!/bin/sh\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	return node
}

// THE FIX FOR THE ONE-BOOT LAG. Generation runs before the stage, so it bakes no interpreter and
// leaves a floor-pending record; the stage installs a node; the regeneration then rewrites the
// launcher to exec it on EVERY exec path, byte-identical to what the next boot's generation
// writes, and removes the record. This replaced
// TestAStageInstalledNodeReachesTheLauncherOnlyAtTheNextGeneration, which pinned the lag.
func TestAStageInstalledNodeReachesTheLauncherOnTheLaunchThatInstalledIt(t *testing.T) {
	e, store := floorLauncherHome(t, "thing", "22.19")
	if err := GenerateAgentLaunchers(e); err != nil {
		t.Fatal(err)
	}
	launcher := filepath.Join(e.LaunchDir(), "thing")
	pending := filepath.Join(e.FloorPendingDir(), "thing")
	atBoot, err := os.ReadFile(launcher)
	if err != nil {
		t.Fatal(err)
	}
	for _, line := range execLinesOf(string(atBoot)) {
		if !strings.Contains(line, `exec "$REAL_BIN" `) {
			t.Errorf("the boot's launcher must not name an interpreter nothing met; got: %s", line)
		}
	}
	if _, err := os.Stat(pending); err != nil {
		t.Fatalf("a launcher whose floor nothing met must leave a floor-pending record: %v", err)
	}

	// The stage installs node@22.19.
	installed := installFakeNode(t, store, "22.19.0")
	var out bytes.Buffer
	if err := RegenerateFloorLaunchers(e.FloorPendingDir(), e.LaunchDir(), []string{"thing"}, &out); err != nil {
		t.Fatalf("RegenerateFloorLaunchers: %v", err)
	}
	regenerated, err := os.ReadFile(launcher)
	if err != nil {
		t.Fatal(err)
	}
	lines := execLinesOf(string(regenerated))
	if len(lines) < 2 {
		t.Fatalf("expected both exec paths in the regenerated launcher, found %v", lines)
	}
	for _, line := range lines {
		if !strings.Contains(line, "exec "+shquote.Quote(installed)+" \"$REAL_BIN\" ") {
			t.Errorf("the regenerated launcher must exec the stage-installed interpreter on every "+
				"exec path; got: %s", line)
		}
	}
	if _, err := os.Stat(pending); !os.IsNotExist(err) {
		t.Errorf("the record must be removed once its launcher is finished: %v", err)
	}
	if !strings.Contains(out.String(), "thing: launcher regenerated to run under "+installed) {
		t.Errorf("the regeneration does not say what it did:\n%s", out.String())
	}

	// And it IS the next boot's launcher, byte for byte.
	if err := GenerateAgentLaunchers(e); err != nil {
		t.Fatal(err)
	}
	nextBoot, err := os.ReadFile(launcher)
	if err != nil {
		t.Fatal(err)
	}
	if string(regenerated) != string(nextBoot) {
		t.Errorf("the regenerated launcher differs from the next generation's:\n--- regenerated\n%s\n"+
			"--- next boot\n%s", regenerated, nextBoot)
	}
	if _, err := os.Stat(pending); !os.IsNotExist(err) {
		t.Errorf("a generation whose floor resolved must leave no record: %v", err)
	}
}

// A launcher whose floor WAS met at generation leaves no record, so the stage has nothing to do
// and a launch that installs nothing pays nothing.
func TestAMetFloorLeavesNoFloorPendingRecord(t *testing.T) {
	e, store := floorLauncherHome(t, "thing", "22.19")
	installFakeNode(t, store, "24.19.0")
	if err := GenerateAgentLaunchers(e); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(e.FloorPendingDir(), "thing")); !os.IsNotExist(err) {
		t.Errorf("a launcher that baked its interpreter left a floor-pending record: %v", err)
	}
}

// A floor still unmet when the regeneration runs is said and left: the launcher keeps its plain
// exec and the record stays, and it is not an error (the bootstrap's refusal owns that case).
// A bin with no record is skipped silently, and a traversal name is refused.
func TestTheRegenerationLeavesWhatItCannotFinish(t *testing.T) {
	e, _ := floorLauncherHome(t, "thing", "22.19")
	if err := GenerateAgentLaunchers(e); err != nil {
		t.Fatal(err)
	}
	before, _ := os.ReadFile(filepath.Join(e.LaunchDir(), "thing"))
	var out bytes.Buffer
	if err := RegenerateFloorLaunchers(e.FloorPendingDir(), e.LaunchDir(), []string{"thing", "other"}, &out); err != nil {
		t.Errorf("an unmet floor and an absent record are not failures: %v", err)
	}
	after, _ := os.ReadFile(filepath.Join(e.LaunchDir(), "thing"))
	if string(before) != string(after) {
		t.Error("the launcher was rewritten although no node meets its floor")
	}
	if _, err := os.Stat(filepath.Join(e.FloorPendingDir(), "thing")); err != nil {
		t.Errorf("the record of an unfinished launcher must stay: %v", err)
	}
	if !strings.Contains(out.String(), "thing: no Node >=22.19 is available") {
		t.Errorf("the unmet floor is not said:\n%s", out.String())
	}
	if strings.Contains(out.String(), "other") {
		t.Errorf("a bin with no record must be skipped silently:\n%s", out.String())
	}
	if err := RegenerateFloorLaunchers(e.FloorPendingDir(), e.LaunchDir(), []string{"../escape"}, &out); err == nil {
		t.Error("a traversal bin name must be refused")
	}
}

// THE BOOTSTRAP CALL SITE. Once a floor is met, by the floor's own install or by the workspace's
// `mise install` before it, the bootstrap hands that floor's launchers to the regeneration with
// the two baked directories. It does so only when a record exists, so a launch whose launchers
// all baked their interpreter costs nothing, and a regeneration that fails is a warning.
func TestTheBootstrapRegeneratesAMetFloorsLaunchers(t *testing.T) {
	const bin = "nodefloor-probe"
	for _, tc := range []struct {
		name     string
		env      []string
		record   bool
		wantCall bool
		wantRC   int
	}{
		{"met by the floor's install", []string{"FAKE_SATISFIED_AFTER_INSTALL=1"}, true, true, 0},
		{"met before it (the workspace's mise install)", []string{"FAKE_SATISFIED=1"}, true, true, 0},
		{"no record: nothing to finish", []string{"FAKE_SATISFIED=1"}, false, false, 0},
		{"refused: nothing is met", []string{"FAKE_MISE_FAIL=1"}, true, false, 78},
	} {
		t.Run(tc.name, func(t *testing.T) {
			b := newFloorBootstrap(t, refusingFixture)
			e := NewEnv(map[string]string{"JAIL_HOME": b.home})
			if tc.record {
				if err := os.MkdirAll(e.FloorPendingDir(), 0o755); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(filepath.Join(e.FloorPendingDir(), bin), []byte("{}"), 0o644); err != nil {
					t.Fatal(err)
				}
			}
			rc, out, calls := b.run(t, tc.env...)
			if rc != tc.wantRC {
				t.Errorf("rc = %d, want %d:\n%s", rc, tc.wantRC, out)
			}
			want := "yolo internal node-floor-launchers --pending=" + e.FloorPendingDir() +
				" --launch=" + e.LaunchDir() + " " + bin
			if got := strings.Contains(calls, want); got != tc.wantCall {
				t.Errorf("regeneration called = %v, want %v (want %q):\n%s", got, tc.wantCall, want, calls)
			}
		})
	}
	t.Run("a failed regeneration warns and the stage goes on", func(t *testing.T) {
		b := newFloorBootstrap(t, refusingFixture)
		e := NewEnv(map[string]string{"JAIL_HOME": b.home})
		if err := os.MkdirAll(e.FloorPendingDir(), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(e.FloorPendingDir(), bin), []byte("{}"), 0o644); err != nil {
			t.Fatal(err)
		}
		rc, out, _ := b.run(t, "FAKE_SATISFIED=1", "FAKE_LAUNCHERS_RC=1")
		if rc != 0 {
			t.Errorf("rc = %d: a regeneration failure must not fail or refuse the stage:\n%s", rc, out)
		}
		if !strings.Contains(out, "were not regenerated; they take the new node at the next boot") {
			t.Errorf("the failure is not said:\n%s", out)
		}
	})
}
