package entrypoint

// hostownedheader_test.go pins the header half of HC-D5 (docs/design/host-computed-layer.md
// §7): the banner an owned host render writes into a real TOML file names the host apply,
// not a jail start, and yolo still recognises either wording as its own.
//
// Measured before the fix: `yolo host apply --assert` under `host_management: own` wrote
// ~/.codex/config.toml under "# Generated by yolo-jail — composed at jail start", on a machine
// where no jail had started. The banner is the file's one statement of who composed it.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mschulkind-oss/yolo-jail/internal/packload"
	"github.com/mschulkind-oss/yolo-jail/internal/render"
)

// jailBanner is the jail notch's banner, spelled by the renderer rather than here.
func jailBanner(t *testing.T) string {
	t.Helper()
	s := surfaceNamed(t, mustEmbeddedPack(t, "codex"), "codex/config")
	return render.Jail(t.TempDir(), t.TempDir(), nil).GeneratedHeader(s)
}

func mustEmbeddedPack(t *testing.T, name string) *packload.Pack {
	t.Helper()
	p, err := embeddedPack(name)
	if err != nil {
		t.Fatal(err)
	}
	return p
}

func TestAnOwnedHostRenderNamesTheHostApplyInItsBanner(t *testing.T) {
	home, path := codexHostHome(t, "model = \"gpt-5\"\n")
	if _, err := RenderHostPack(mustEmbeddedPack(t, "codex"), home, render.OwnershipOwn, false, nil); err != nil {
		t.Fatalf("owned RenderHostPack(codex): %v", err)
	}
	written, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	head := string(written)
	if i := strings.Index(head, "\n\n"); i >= 0 {
		head = head[:i]
	}
	if !strings.HasPrefix(head, "# Generated by yolo-jail") {
		t.Fatalf("the owned host render wrote no banner:\n%s", written)
	}
	if strings.Contains(head, "jail start") {
		t.Errorf("the owned host render's banner says the file was composed at a jail start, "+
			"at the host notch:\n%s", head)
	}
	if !strings.Contains(head, "yolo host apply") {
		t.Errorf("the owned host render's banner does not name `yolo host apply`, the command "+
			"that composed the file:\n%s", head)
	}
}

// A JAIL KEEPS ITS OWN WORDS: the banner is per notch, not replaced everywhere.
func TestAJailBootKeepsTheJailBanner(t *testing.T) {
	e := codexComputedEnv(t, "")
	if err := ConfigurePackByName(e, "codex"); err != nil {
		t.Fatal(err)
	}
	written := readFile(t, filepath.Join(e.Home, ".codex", "config.toml"))
	if !strings.HasPrefix(written, jailBanner(t)) {
		t.Errorf("the jail boot's codex config does not start with the jail banner %q:\n%s",
			jailBanner(t), written)
	}
	if strings.Contains(written, "yolo host apply") {
		t.Errorf("the jail boot's banner names the host apply:\n%s", written)
	}
}

// A FILE AN OLDER HOST YOLO WROTE carries the jail's banner, and that banner is still yolo's:
// the owned render's comment-loss probe must not read it as the user's comments, or every
// home upgraded from such a yolo reports a loss it cannot have.
func TestAnOwnedRenderDoesNotReportAnOlderBannerAsYourComments(t *testing.T) {
	home, _ := codexHostHome(t, jailBanner(t)+"model = \"gpt-5\"\n")
	res, err := RenderHostPack(mustEmbeddedPack(t, "codex"), home, render.OwnershipOwn, true, nil)
	if err != nil {
		t.Fatalf("owned observe RenderHostPack(codex): %v", err)
	}
	if r := resultFor(t, res, "codex/config"); len(r.Formatting) != 0 {
		t.Errorf("a file holding only yolo's older banner reported a comment loss: %q", r.Formatting)
	}
}
