#!/usr/bin/env bash
# Install `yolo-go` as a standalone command alongside `yolo` — no env flip.
#
#   yolo      -> the Python CLI (unchanged; `just install`)
#   yolo-go   -> the Go front door (installed by this script)
#
# Both work on the host. Inside a jail the command is ALWAYS `yolo` (the agent
# can't tell which impl it is): launching a jail with `yolo-go` forwards
# YOLO_IMPL=go into the container (seam #11), so the in-jail `yolo`
# transparently runs Go; launching with plain `yolo` leaves the in-jail `yolo`
# on Python. Unported subcommands delegate back to Python in both places.
#
# The wrapper bakes the gate env in, so callers just run `yolo-go` — no flip.
# Rebuild binaries with `just build-go` and re-run this after moving the repo.
#
# Usage:
#   ./scripts/go-front-door.sh          # install ~/.local/bin/yolo-go (default)
#   ./scripts/go-front-door.sh --env    # instead PRINT export lines to eval
set -euo pipefail

MODE="install"
[ "${1:-}" = "--env" ] && MODE="env"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GOOS="$(go env GOOS)"
GOARCH="$(go env GOARCH)"
BIN_DIR="${REPO_ROOT}/dist-go/${GOOS}-${GOARCH}"
GO_YOLO="${BIN_DIR}/yolo"

if [ ! -x "$GO_YOLO" ]; then
    echo "go-front-door: ${GO_YOLO} not found — run \`just build-go\` first." >&2
    exit 1
fi

# The venv python that can import src.cli (editable install) — handed to the Go
# binary as YOLO_PYTHON so its delegate-to-Python path works from any cwd on the
# host. (In-jail, seam #11 sets its own YOLO_PYTHON.)
VENV_PY="$(env -u VIRTUAL_ENV uv run --project "$REPO_ROOT" python -c 'import sys; print(sys.executable)')"

if [ "$MODE" = "env" ]; then
    cat >&2 <<EOF
Go front door env (eval the stdout to apply to THIS shell):
  eval "\$(./scripts/go-front-door.sh --env)"
Prefer \`just install-go\` for a standalone \`yolo-go\` command (no flip).
EOF
    cat <<EOF
export YOLO_IMPL=go
export YOLO_GO_BIN_DIR="${BIN_DIR}"
export YOLO_PYTHON="${VENV_PY}"
export YOLO_REPO_ROOT="${REPO_ROOT}"
EOF
    exit 0
fi

DEST="${YOLO_GO_INSTALL_DIR:-$HOME/.local/bin}"
mkdir -p "$DEST"
WRAPPER="${DEST}/yolo-go"

cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Generated by scripts/go-front-door.sh (\`just install-go\`) — the go-port A/B
# front door. \`yolo\` stays Python; this is the Go one. Regenerate after moving
# the repo or a \`just build-go\`.
export YOLO_IMPL=go
export YOLO_GO_BIN_DIR="${BIN_DIR}"
export YOLO_PYTHON="${VENV_PY}"
export YOLO_REPO_ROOT="${REPO_ROOT}"
exec "${GO_YOLO}" "\$@"
EOF
chmod +x "$WRAPPER"

echo "installed ${WRAPPER}"
echo "  host: 'yolo' = Python (unchanged), 'yolo-go' = Go"
echo "  jail: always 'yolo' — Go when launched via yolo-go, Python via yolo"
echo "  native now: run, check, doctor, ps  (rest delegate to Python)"
case ":${PATH}:" in
    *":${DEST}:"*) ;;
    *) echo "  NOTE: ${DEST} is not on PATH — add it to run \`yolo-go\` directly." ;;
esac
