package config

import (
	"github.com/mschulkind-oss/yolo-jail/internal/jsonx"
)

// agentupdates.go is the HOST half of the `agent_updates` policy
// (docs/design/program-delivery.md §3.5, OQ-PD12). The JAIL half — the launcher generator
// that reads YOLO_AGENT_UPDATES and bakes a 0/1 into each script — is
// internal/entrypoint/agentupdates.go.

// agentUpdatesKey is the top-level opt-OUT of evergreen agent dependencies.
const agentUpdatesKey = "agent_updates"

// AgentUpdatesWire renders the user's `agent_updates` value as the JSON the jail reads out
// of YOLO_AGENT_UPDATES, or "" when the key is absent.
//
// # The value, and why it is a pack name
//
// Either a bool or a per-pack map with `"*"` as the default key:
//
//	"agent_updates": false                              // every agent frozen
//	"agent_updates": { "*": true, "claude": false }     // all but claude
//
// THE KEY IS A PACK NAME, NOT A BIN NAME. One pack may declare more than one program, and
// the unit a user reasons about is the pack they selected. A specific key beats `"*"`;
// `"*"` beats absence; absence is `true`.
//
// # Why it is read from the USER config directly
//
// The same construction `packs`, `host_wrappers` and `host_apply_on_launch` use, and the
// reason here is the same one `packs` has: a workspace config travels with the repo and is
// AGENT-EDITABLE (/workspace is bind-mounted rw). A key that let whatever is running in the
// jail freeze its own updates would hand the agent the switch — so workspace scope is made
// INEXPRESSIBLE rather than merely refused, and validateAgentUpdates' error is
// defense-in-depth against a silent no-op, not the boundary itself.
//
// A pack may not opt itself out either: the pack declares HOW to update (OQ-PD14), never
// WHETHER to.
//
// # The default direction INVERTS the nearest precedent, deliberately
//
// HostApplyOnLaunchEnabled fails CLOSED — an unreadable config has not granted an opt-in to
// write into the user's real home. This key is an opt-OUT of a policy that is on by ruling,
// so absent, empty or unreadable means TRUE. A faithful copy of that file would silently
// freeze every agent in every jail, which is both the state §3.5 exists to end and the one
// nobody would notice.
//
// An empty string is emitted for an absent key rather than "true", because the wire
// variable is set on every launch: an absent VALUE and an absent VARIABLE then mean the
// same thing to the jail (the reader defaults open either way), which keeps a launcher
// generated by an older host from reading differently than one generated by this one.
func AgentUpdatesWire() string {
	return agentUpdatesWire(UserScopeConfigOrEmpty())
}

// agentUpdatesWire is the reading, split from the real-home lookup so the validator and
// the tests exercise one implementation — the split hostApplyOnLaunchValue makes, for the
// same reason.
func agentUpdatesWire(cfg *jsonx.OrderedMap) string {
	v, present := cfg.Get(agentUpdatesKey)
	if !present || v == nil {
		return ""
	}
	wire, err := jsonx.DumpsCompact(v)
	if err != nil {
		return ""
	}
	return wire
}

// agentUpdatesProblem reports why a value is not a usable `agent_updates`, or "" when its
// SHAPE is fine. Shared by the validator and by nothing else today; it exists as a
// function so the accepted shapes are stated once.
func agentUpdatesProblem(v any) string {
	switch t := v.(type) {
	case bool:
		return ""
	case *jsonx.OrderedMap:
		for _, k := range t.Keys() {
			val, _ := t.Get(k)
			if _, ok := val.(bool); !ok {
				return "every entry must be a boolean; " + pyReprValue(k) + " is " + pyReprValue(val)
			}
		}
		return ""
	default:
		return "expected a boolean or an object mapping pack names to booleans (got " +
			pyReprValue(v) + ")"
	}
}
