package integration

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	goruntime "runtime"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/mschulkind-oss/yolo-jail/internal/macosuser"
)

// sharedUsersDir is where a fixture workspace has to live, and it is NOT
// macosuser.SharedRootDefault(): that is /Users/Shared/yolo, which `yolo macos-setup`
// creates and this suite deliberately does not require. /Users/Shared is stock macOS,
// mode 1777, present before anything of ours has run — which is what lets the policy
// assertions report on a Mac where the account setup has not happened or has failed.
const sharedUsersDir = "/Users/Shared"

// THE POLICY SUITE: a command run under the GENERATED profile, and the kernel's answer.
//
// WHY THIS FILE EXISTS. Sixteen tests in internal/macosuser pin what SeatbeltProfile
// emits — the clauses, the escaping, the last-match-wins ordering — and not one of them
// asks whether the emitted text denies anything. docs/research/agent-safehouse.md §8.1
// names that as the worst value-to-cost gap this backend has, one level up from the
// "pins the callee while the call site is unpinned" class AGENTS.md warns about: the
// tests pin the string, and nothing pins that the string does something. Agent
// Safehouse, the comparison that surfaced it, runs 389 bats cases that execute a
// command under their profile and assert the refusal.
//
// EVERY CASE HAS A CONTROL, and that is what makes it a measurement rather than a
// coincidence. `cat /Library/Keychains/…` failing inside the sandbox proves nothing on
// its own — it could be a missing file, a permission bit, SIP. So each case runs the
// SAME script twice: once bare, where it must succeed, and once under the profile,
// where it must be refused. A case whose bare control fails is reported as a broken
// control, loudly, rather than counted as a pass — a machine where the control stopped
// working is exactly the early warning the floating `macos-latest` label in
// .github/workflows/macos-user.yml exists to give.
//
// THE GATE IS NARROWER THAN A LAUNCH'S, deliberately. requireMacosUser needs the
// _yolojail account, a shared root and passwordless sudo, because it launches. This
// needs `sandbox-exec` and a writable /Users/Shared, because it loads a profile and
// runs /bin/sh under it. So the policy suite still reports on a Mac where
// `yolo macos-setup` has not run or has failed — which is the one machine state where
// knowing whether the profile still denies things is most useful.
//
// WHAT THIS SUITE IS NOT. It is not a launch: nothing here runs `yolo`, builds a nix
// closure, or becomes the sandbox user. The profile it loads is the one BuildRunPlan
// would install, generated by the same function with the same arguments, and the
// separate question of whether a launch actually hands that profile to the agent is
// pinned by internal/macosuser/launchconfinement_test.go.
//
// STDIN IS A PIPE FOR EVERY RUN, and it is not incidental. Go gives a child with no
// Stdin the /dev/null DEVICE, which is a vnode — so `isatty(0)` on it is a
// `file-ioctl` on a path, which the profile now denies, and the caller sees EPERM where
// it expected ENOTTY. A pipe has no path and never reaches that check. Anything that
// treats an ioctl error as fatal rather than as "not a terminal" would fail here for a
// reason that has nothing to do with the case under test.

// ---------------------------------------------------------------------------
// The registry: every #seatbelt-test-id: in the profile, and what proves it.
// ---------------------------------------------------------------------------

// seatbeltRule is one rule id in the generated profile. `unproven` is empty when at
// least one runtime case below carries the id, and otherwise says why no case can —
// which is the point of the registry: the negative space is WRITTEN DOWN instead of
// being the silence left by a case nobody wrote.
type seatbeltRule struct {
	id       string
	unproven string
}

// seatbeltRules must name every id the profile carries, and only those.
// TestMacosUserSeatbeltRegistryMatchesTheProfile enforces both directions on Linux,
// under -short, so a deny added without a proof is caught on the machine that develops
// this repo rather than on the nightly.
var seatbeltRules = []seatbeltRule{
	{id: "write-outside-deny"},
	{id: "workspace-write-allow"},
	{id: "workspace-readonly-deny"},
	{id: "volumes-read-deny"},
	{id: "boot-volume-read-allow", unproven: "/Volumes/Macintosh HD is not on every Mac — " +
		"an APFS boot volume is mounted at / and the /Volumes entry is a synthetic link " +
		"that a CI runner does not always carry. The bare control would decide the case " +
		"rather than the profile, which is the one thing a control may not do."},
	{id: "raw-device-deny"},
	{id: "users-read-deny"},
	{id: "workspace-read-allow"},
	{id: "library-keychains-deny"},
	{id: "system-keychains-deny"},
	{id: "cross-process-procargs-deny"},
	{id: "cross-process-pidinfo-deny"},
	{id: "same-sandbox-pidinfo-allow"},
	{id: "file-ioctl-deny", unproven: "there is no shell-level ioctl on a non-terminal " +
		"that succeeds UNSANDBOXED: an ioctl on a regular file or a pipe returns ENOTTY " +
		"on its own, and the device ioctls that would succeed (a raw disk) need root. " +
		"With no bare control that succeeds, a refusal inside the sandbox proves nothing. " +
		"What is measured instead is the allow beside it — file-ioctl-tty-allow runs a " +
		"real pty through `script`, which fails if the deny is wider than the re-allow."},
	{id: "file-ioctl-tty-allow"},
}

// ---------------------------------------------------------------------------
// The cases.
// ---------------------------------------------------------------------------

// seatbeltWant is what the SANDBOXED run must show. The bare run is the control and its
// expectation is fixed: it must succeed, and for markerHidden it must show the marker.
type seatbeltWant int

const (
	// wantRefused: the sandboxed run exits non-zero. The bare run exits zero.
	wantRefused seatbeltWant = iota
	// wantAllowed: the sandboxed run prints seatbeltOK, like the bare run. A marker
	// rather than an exit code because several probes here exit zero having done
	// nothing (`script` reports its own status, not its child's).
	wantAllowed
	// wantMarkerHidden: the bare run prints the fixture's marker and the sandboxed run
	// does not. The shape cross-process argv needs, where the refusal is invisible —
	// `ps` prints a shorter line rather than failing.
	wantMarkerHidden
)

// seatbeltOK is what a wantAllowed script prints when the operation really happened.
const seatbeltOK = "SEATBELT_OK"

// seatbeltFixtures is the tree every script is written against. ws is the granted
// workspace, root its (traversal-only) parent, outside a sibling of ws under that
// parent — a real checkout beside the granted one, which is the case the (literal)
// ancestor grants exist to keep denied.
type seatbeltFixtures struct {
	root     string // /Users/Shared/yolo-sb-XXXX — traversal only
	ws       string // <root>/ws                   — granted, read+write
	readonly string // <root>/ws/vendored          — config.workspace_readonly
	outside  string // <root>/outside              — denied
	// neutral is a path under /private/var/tmp: READ-ALLOWED by the base policy and
	// outside the writable set. It is what isolates the write deny — a probe under
	// /Users would be refused by the read deny too, and the case could not say which
	// directive did it.
	neutral    string
	canaryPID  int    // a process spawned OUTSIDE the sandbox
	canaryWord string // a word on that process's command line
}

type seatbeltCase struct {
	name string
	id   string // the #seatbelt-test-id: in the profile this proves
	// why the case is written the way it is — printed on failure, because a policy
	// refusal with no explanation is a line nobody can act on.
	why    string
	script func(seatbeltFixtures) string
	want   seatbeltWant
}

// seatbeltCases is the whole suite. It is a pure function of the fixtures so the
// registry test can walk it on Linux.
func seatbeltCases() []seatbeltCase {
	return []seatbeltCase{
		{
			name: "workspace_write_allowed",
			id:   "workspace-write-allow",
			why: "the positive control for the entire write policy. Without it a profile " +
				"that denied every write would pass every refusal case in this file.",
			script: func(f seatbeltFixtures) string {
				return "touch " + sh(f.ws+"/probe") + " && echo " + seatbeltOK
			},
			want: wantAllowed,
		},
		{
			name: "workspace_read_allowed",
			id:   "workspace-read-allow",
			why:  "the /Users read deny must not reach the granted workspace itself.",
			script: func(f seatbeltFixtures) string {
				return "cat " + sh(f.ws+"/seed")
			},
			want: wantAllowed,
		},
		{
			name: "ancestor_grant_does_not_reach_downward",
			id:   "users-read-deny",
			why: "the workspace's intermediate directories are granted (literal), not " +
				"(subpath). A literal names one node, so the chain can be walked and the " +
				"SIBLING CHECKOUTS under it stay denied; a (subpath) grant there would " +
				"re-expose every neighbour, which is the isolation the /Users deny is for. " +
				"This case is what tells the two spellings apart — it passes under a " +
				"literal grant and fails under a subpath one.",
			script: func(f seatbeltFixtures) string { return "ls " + sh(f.outside) },
			want:   wantRefused,
		},
		{
			name: "ancestor_stat_allowed",
			id:   "workspace-read-allow",
			why: "the other half of the same grant: `git ls-files` stats up the chain " +
				"looking for the repo boundary, and a denied ancestor made `just format` " +
				"die as \"Invalid path: Operation not permitted\" on real hardware.",
			script: func(f seatbeltFixtures) string {
				return "test -d " + sh(f.root) + " && echo " + seatbeltOK
			},
			want: wantAllowed,
		},
		{
			name: "write_outside_the_writable_set_refused",
			id:   "write-outside-deny",
			why: "a path under /private/var/tmp, which the base policy READ-allows and the " +
				"writable set does not name — so the write deny is the only directive that " +
				"can refuse it. A probe under /Users would be refused by the read deny too " +
				"and the case could not say which one did it. Self-cleaning, because the " +
				"bare control really does create the file.",
			script: func(f seatbeltFixtures) string {
				return "touch " + sh(f.neutral) + " && rm -f " + sh(f.neutral)
			},
			want: wantRefused,
		},
		{
			name: "read_a_sibling_checkout_refused",
			id:   "users-read-deny",
			why:  "another directory beside the workspace is what the /Users read deny is for.",
			script: func(f seatbeltFixtures) string {
				return "cat " + sh(f.outside+"/secret")
			},
			want: wantRefused,
		},
		{
			name: "workspace_readonly_write_refused",
			id:   "workspace-readonly-deny",
			why: "config.workspace_readonly. It was accepted and silently ignored on this " +
				"backend until 2026-08-23 — a security key that lies — and it is inside " +
				"the writable set, so only the later deny can refuse it.",
			script: func(f seatbeltFixtures) string {
				return "touch " + sh(f.readonly+"/hook")
			},
			want: wantRefused,
		},
		{
			name:   "volumes_listing_refused",
			id:     "volumes-read-deny",
			why:    "an attached volume is somebody's backup disk.",
			script: func(seatbeltFixtures) string { return "ls /Volumes" },
			want:   wantRefused,
		},
		{
			name: "raw_device_metadata_refused",
			id:   "raw-device-deny",
			why: "the deny is file-read*, which includes METADATA, so a stat is refused " +
				"without needing the root privileges a read of the device itself would.",
			script: func(seatbeltFixtures) string { return "ls -l /dev/disk0" },
			want:   wantRefused,
		},
		{
			name: "library_keychains_refused",
			id:   "library-keychains-deny",
			why: "System.keychain is 0644 on stock macOS, so this deny is load-bearing " +
				"rather than a restatement of the file mode. Measured by hand on hardware " +
				"2026-09-12 (docs/plans/runbooks/macos-user-manual-checks.md item 10a); " +
				"this is the same probe, asserted continuously.",
			script: func(seatbeltFixtures) string { return "ls /Library/Keychains" },
			want:   wantRefused,
		},
		{
			name: "system_keychains_refused",
			id:   "system-keychains-deny",
			why: "the deny agent-safehouse.md §3.2 found missing beside the one above: " +
				"/Library/Keychains was denied and /System/Library/Keychains was not.",
			script: func(seatbeltFixtures) string { return "ls /System/Library/Keychains" },
			want:   wantRefused,
		},
		{
			name: "cross_process_argv_hidden",
			id:   "cross-process-procargs-deny",
			why: "another process's command line is where a secret sits in plain sight — " +
				"an API key passed as a flag, a token in an env dump. The refusal is " +
				"INVISIBLE (ps prints a shorter line, it does not fail), which is why this " +
				"case asserts a missing marker rather than an exit code.",
			script: func(f seatbeltFixtures) string {
				return "ps -ww -o args= -p " + strconv.Itoa(f.canaryPID) + " || true"
			},
			want: wantMarkerHidden,
		},
		{
			name: "cross_process_argv_hidden_via_pidinfo",
			id:   "cross-process-pidinfo-deny",
			why: "the SAME probe, registered against the second directive on purpose: " +
				"Safehouse determined empirically on macOS 26 that EITHER the procargs " +
				"sysctl OR process-info-pidinfo serves this read, so one case proves the " +
				"pair and deleting either directive alone must turn it red.",
			script: func(f seatbeltFixtures) string {
				return "ps -ww -o args= -p " + strconv.Itoa(f.canaryPID) + " || true"
			},
			want: wantMarkerHidden,
		},
		{
			name: "same_sandbox_process_info_allowed",
			id:   "same-sandbox-pidinfo-allow",
			why: "what the re-allow buys, and the reason the deny above is survivable: a " +
				"process may still inspect ITSELF and its own children. lsof reads open " +
				"file descriptors through proc_pidinfo, so it produces no lines at all " +
				"when the re-allow is dropped. Asserted on OUTPUT rather than exit status, " +
				"which lsof varies for reasons of its own.",
			script: func(seatbeltFixtures) string {
				return "/usr/sbin/lsof -p $$ 2>/dev/null | grep -q . && echo " + seatbeltOK
			},
			want: wantAllowed,
		},
		{
			name: "pty_ioctls_allowed",
			id:   "file-ioctl-tty-allow",
			why: "`script` allocates a REAL pty — /dev/ptmx, then the /dev/ttysNNN slave — " +
				"and `stty` on it is the terminal ioctl every agent TUI depends on. This " +
				"is the case that fails if the tty re-allow is narrower than the terminals " +
				"an agent's tooling actually opens, which is the part of the file-ioctl " +
				"restriction that was written blind.",
			script: func(seatbeltFixtures) string {
				return "script -q /dev/null /bin/sh -c 'stty -a >/dev/null 2>&1 && echo " + seatbeltOK + "'"
			},
			want: wantAllowed,
		},
	}
}

// ---------------------------------------------------------------------------
// The runtime test.
// ---------------------------------------------------------------------------

// TestMacosUserSeatbeltProfileEnforcesItsRules loads the generated profile with
// sandbox-exec and asks the kernel about every case above.
func TestMacosUserSeatbeltProfileEnforcesItsRules(t *testing.T) {
	requireMacosUserSeatbelt(t)
	f := seatbeltFixture(t)
	profile := seatbeltProfileFile(t, f)

	for _, tc := range seatbeltCases() {
		t.Run(tc.name, func(t *testing.T) {
			script := tc.script(f)
			bareOut, bareRC := runScript(t, script, nil)
			// THE CONTROL, always first. Every case is a claim that the SANDBOX is what
			// refused; a bare run that cannot do the thing either makes the case say
			// nothing at all, so it is a failure rather than a skip.
			if bareRC != 0 {
				t.Fatalf("the CONTROL failed: `%s` exits %d unsandboxed, so this case cannot "+
					"tell a policy refusal from a machine that never allowed it.\n"+
					"rule: %s\nwhy:  %s\noutput:\n%s", script, bareRC, tc.id, tc.why, bareOut)
			}
			sbOut, sbRC := runScript(t, script, []string{"/usr/bin/sandbox-exec", "-f", profile})

			switch tc.want {
			case wantRefused:
				if sbRC == 0 {
					t.Errorf("NOT REFUSED. `%s` succeeded under the profile.\n"+
						"rule: #seatbelt-test-id:%s#\nwhy:  %s\noutput:\n%s",
						script, tc.id, tc.why, sbOut)
				}
			case wantAllowed:
				if !strings.Contains(sbOut, seatbeltOK) {
					t.Errorf("REFUSED, and should not have been. `%s` did not report %s under "+
						"the profile (rc %d).\nrule: #seatbelt-test-id:%s#\nwhy:  %s\noutput:\n%s",
						script, seatbeltOK, sbRC, tc.id, tc.why, sbOut)
				}
			case wantMarkerHidden:
				if !strings.Contains(bareOut, f.canaryWord) {
					t.Fatalf("the CONTROL failed: the canary's marker %q is absent from the "+
						"unsandboxed output, so its absence under the profile would prove "+
						"nothing.\noutput:\n%s", f.canaryWord, bareOut)
				}
				if strings.Contains(sbOut, f.canaryWord) {
					t.Errorf("NOT HIDDEN. The command line of a process outside the sandbox is "+
						"still readable from inside it (marker %q).\n"+
						"rule: #seatbelt-test-id:%s#\nwhy:  %s\noutput:\n%s",
						f.canaryWord, tc.id, tc.why, sbOut)
				}
			}
		})
	}
}

// ---------------------------------------------------------------------------
// The registry check — pure, and it runs on Linux.
// ---------------------------------------------------------------------------

// TestMacosUserSeatbeltRegistryMatchesTheProfile is the greppability convention made
// mechanical, in both directions: a rule with no proof and no stated reason fails here,
// and so does a proof for a rule that no longer exists.
//
// It runs under -short, on Linux, WITHOUT the gate — which is the point. The machines
// that develop this repo cannot load a Seatbelt profile, so if this check waited for a
// Mac, a deny added today would sit unproven until the next nightly at the earliest.
func TestMacosUserSeatbeltRegistryMatchesTheProfile(t *testing.T) {
	profile := macosuser.SeatbeltProfile("/Users/Shared/proj", "", []string{"vendored"})

	inProfile := map[string]bool{}
	for _, m := range seatbeltIDPattern.FindAllStringSubmatch(profile, -1) {
		inProfile[m[1]] = true
	}
	if len(inProfile) == 0 {
		t.Fatal("the profile carries no #seatbelt-test-id:…# markers at all — either the " +
			"convention was removed or this test is reading the wrong text")
	}

	registered := map[string]seatbeltRule{}
	for _, r := range seatbeltRules {
		if _, dup := registered[r.id]; dup {
			t.Errorf("rule %q is registered twice", r.id)
		}
		registered[r.id] = r
		if !inProfile[r.id] {
			t.Errorf("rule %q is registered here but is not in the profile; either the "+
				"directive was deleted and this entry outlived it, or the id was renamed "+
				"on one side only", r.id)
		}
	}
	for id := range inProfile {
		if _, ok := registered[id]; !ok {
			t.Errorf("the profile carries #seatbelt-test-id:%s# and nothing here claims it. "+
				"Add a case to seatbeltCases, or a seatbeltRules entry saying why no case "+
				"can prove it — an unregistered rule is one nobody will notice is untested.", id)
		}
	}

	proved := map[string]int{}
	for _, tc := range seatbeltCases() {
		if _, ok := registered[tc.id]; !ok {
			t.Errorf("case %q names rule %q, which is in no registry entry", tc.name, tc.id)
		}
		proved[tc.id]++
	}
	for _, r := range seatbeltRules {
		switch {
		case r.unproven == "" && proved[r.id] == 0:
			t.Errorf("rule %q claims to be proved at runtime and no case carries its id", r.id)
		case r.unproven != "" && proved[r.id] > 0:
			t.Errorf("rule %q is registered as unproven and %d case(s) carry its id; delete "+
				"the reason or delete the cases, but the file must not say both", r.id, proved[r.id])
		}
	}
}

// seatbeltIDPattern is the marker seatbelt.go embeds beside each deny. Spelled here
// rather than exported from that package: two independent readers of one convention is
// what makes a silent rename show up as a failure instead of as agreement.
var seatbeltIDPattern = regexp.MustCompile(`#seatbelt-test-id:([a-z0-9-]+)#`)

// ---------------------------------------------------------------------------
// The gate.
// ---------------------------------------------------------------------------

// seatbeltHost is what a policy assertion needs, which is much less than a launch
// needs: no _yolojail account, no sudo, no nix closure. A struct of FACTS so the
// decision stays pure and table-testable on Linux, where none of them can be produced —
// the same shape as macosUserHost, for the same reason.
type seatbeltHost struct {
	short          bool
	goos           string
	sandboxExec    bool // /usr/bin/sandbox-exec is there to load a profile with
	sharedWritable bool // /Users/Shared admits a fixture, which is where one must live
}

// gate returns the reason this host cannot assert the policy, or ok. Ordered
// most-fundamental-first so the reason a reader gets is the one to act on.
func (h seatbeltHost) gate() (reason string, ok bool) {
	switch {
	case h.short:
		return "skipping under -short: this loads a real Seatbelt profile", false
	case h.goos != "darwin":
		return fmt.Sprintf("Seatbelt is darwin-only and GOOS is %s — there is no "+
			"sandbox-exec here, so the profile is text and nothing more", h.goos), false
	case !h.sandboxExec:
		return "/usr/bin/sandbox-exec is absent, so no profile can be loaded. On a macOS " +
			"release that finally removed the Apple-deprecated tool this is the signal " +
			"that the whole backend needs rethinking, not a machine to fix", false
	case !h.sharedWritable:
		return fmt.Sprintf("%s does not admit a directory, and the fixture must live "+
			"there: the profile grants the workspace by path and denies the rest of "+
			"/Users, so a workspace under /var/folders would be inside the writable set "+
			"already and every write case would pass for the wrong reason",
			sharedUsersDir), false
	}
	return "", true
}

// probeSeatbeltHost measures the facts gate() decides on.
func probeSeatbeltHost() seatbeltHost {
	h := seatbeltHost{short: testing.Short(), goos: goruntime.GOOS}
	if h.goos != "darwin" {
		return h
	}
	if _, err := exec.LookPath("sandbox-exec"); err == nil {
		h.sandboxExec = true
	}
	if d, err := os.MkdirTemp(sharedUsersDir, "yolo-sb-probe-"); err == nil {
		h.sharedWritable = true
		_ = os.RemoveAll(d)
	}
	return h
}

// macosUserGateSeatbelt is this gate's name in the ledger. The verdict is computed PER
// GATE (macosUserVacuityVerdict), so a run that satisfied this cheap gate while every
// test behind the launch gate skipped is failed rather than counted green.
const macosUserGateSeatbelt = "seatbelt"

// requireMacosUserSeatbelt is the gate, and it files into the SAME ledger
// requireMacosUser uses (integration/macosusergate_test.go) so that a declared macOS
// run in which these all skip is still a failed run. A second ledger would be a second
// way for the suite to pass vacuously.
func requireMacosUserSeatbelt(t *testing.T) {
	t.Helper()
	if !macosUserTestNameOK(t.Name()) {
		t.Fatalf("%s does not start with %q; the macOS job selects this suite with "+
			"`-run '^%s'` and a test outside that pattern never runs",
			t.Name(), macosUserTestPrefix, macosUserTestPrefix)
	}
	reason := "the test skipped after passing the gate — see its own skip message"
	t.Cleanup(func() {
		macosUserTests.record(macosUserOutcomeFor(t.Name(), t.Skipped(), reason, macosUserGateSeatbelt))
	})
	if why, ok := probeSeatbeltHost().gate(); !ok {
		reason = why
		t.Skip("macos-user seatbelt: " + why)
	}
}

// TestMacosUserSeatbeltGateAdmitsAMacWithSandboxExec: the positive case first, because
// a gate that skips everywhere is the failure the whole ledger exists to catch.
func TestMacosUserSeatbeltGateAdmitsAMacWithSandboxExec(t *testing.T) {
	h := seatbeltHost{goos: "darwin", sandboxExec: true, sharedWritable: true}
	if reason, ok := h.gate(); !ok {
		t.Fatalf("the gate refused a Mac that can load a profile: %s", reason)
	}
}

// TestMacosUserSeatbeltGateRefusesWhatCannotLoadAProfile, one broken fact at a time.
func TestMacosUserSeatbeltGateRefusesWhatCannotLoadAProfile(t *testing.T) {
	ok := seatbeltHost{goos: "darwin", sandboxExec: true, sharedWritable: true}
	cases := []struct {
		name  string
		host  seatbeltHost
		names string
	}{
		{"short", func() seatbeltHost { h := ok; h.short = true; return h }(), "-short"},
		{"linux", func() seatbeltHost { h := ok; h.goos = "linux"; return h }(), "darwin-only"},
		{"no-sandbox-exec", func() seatbeltHost { h := ok; h.sandboxExec = false; return h }(), "sandbox-exec"},
		{"no-shared-root", func() seatbeltHost { h := ok; h.sharedWritable = false; return h }(), "/Users/Shared"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			reason, admitted := tc.host.gate()
			if admitted {
				t.Fatalf("the gate admitted a host that cannot load a profile (%s)", tc.name)
			}
			if !strings.Contains(reason, tc.names) {
				t.Errorf("the skip reason does not name %q, so a reader of the CI log "+
					"cannot act on it:\n%s", tc.names, reason)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// Fixtures and the two runners.
// ---------------------------------------------------------------------------

// seatbeltFixture builds the tree the cases are written against and starts the canary.
//
// IT CANNOT BE t.TempDir(), and the reason is the profile rather than permissions: on
// darwin that is /var/folders, which the profile puts in the WRITABLE SET outright, so
// a workspace there would make every write case pass whether or not the workspace grant
// exists. Under /Users/Shared the workspace is inside the /Users read deny and is
// reachable only through the grants this suite is measuring.
func seatbeltFixture(t *testing.T) seatbeltFixtures {
	t.Helper()
	root, err := os.MkdirTemp(sharedUsersDir, "yolo-sb-")
	if err != nil {
		t.Fatalf("creating the fixture root under %s: %v", sharedUsersDir, err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(root) })
	resolved, err := filepath.EvalSymlinks(root)
	if err != nil {
		t.Fatalf("resolving %s: %v", root, err)
	}
	f := seatbeltFixtures{
		root:     resolved,
		ws:       filepath.Join(resolved, "ws"),
		readonly: filepath.Join(resolved, "ws", "vendored"),
		outside:  filepath.Join(resolved, "outside"),
		neutral: filepath.Join("/private/var/tmp",
			fmt.Sprintf("yolo-sb-write-%d-%d", os.Getpid(), time.Now().UnixNano())),
	}
	t.Cleanup(func() { _ = os.Remove(f.neutral) })
	for _, d := range []string{f.ws, f.readonly, f.outside} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			t.Fatalf("creating %s: %v", d, err)
		}
	}
	for path, content := range map[string]string{
		filepath.Join(f.ws, "seed"):        seatbeltOK + "\n",
		filepath.Join(f.outside, "secret"): "a sibling checkout's private file\n",
	} {
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatalf("writing %s: %v", path, err)
		}
	}
	f.canaryPID, f.canaryWord = startSeatbeltCanary(t)
	return f
}

// startSeatbeltCanary spawns a process OUTSIDE the sandbox whose command line carries a
// word nothing else on the machine has, and returns its pid and that word.
//
// Outside is the whole point: `same-sandbox` re-allows the inspection of processes in
// the same sandbox, so a canary started from inside would be the case that is supposed
// to keep working rather than the one that must be refused.
func startSeatbeltCanary(t *testing.T) (int, string) {
	t.Helper()
	word := fmt.Sprintf("yolo-seatbelt-canary-%d-%d", os.Getpid(), time.Now().UnixNano())
	// A `while` loop rather than `sleep`, because a shell execs a single simple command
	// in place and the marker would go with the old argv.
	cmd := exec.Command("/bin/sh", "-c", "while :; do sleep 1; done # "+word)
	if err := cmd.Start(); err != nil {
		t.Fatalf("starting the argv canary: %v", err)
	}
	t.Cleanup(func() {
		_ = cmd.Process.Kill()
		_, _ = cmd.Process.Wait()
	})
	// Wait for it to be visible before any case reads it, so a slow fork is not
	// mistaken for a policy that hid it.
	deadline := time.Now().Add(10 * time.Second)
	for time.Now().Before(deadline) {
		out, _ := runScript(t, "ps -ww -o args= -p "+strconv.Itoa(cmd.Process.Pid)+" || true", nil)
		if strings.Contains(out, word) {
			return cmd.Process.Pid, word
		}
		time.Sleep(200 * time.Millisecond)
	}
	t.Fatalf("the argv canary (pid %d, marker %s) never became visible to `ps` "+
		"unsandboxed, so the cross-process cases have no control", cmd.Process.Pid, word)
	return 0, ""
}

// seatbeltProfileFile writes the generated profile where sandbox-exec can read it.
//
// The arguments are the ones BuildRunPlan passes (runplan.go): the workspace, the real
// sandbox home, and the workspace_readonly list — so the text under test is the text a
// launch would install, not a second profile written for the occasion. It is left in
// the temp dir on failure and its path is logged, because the first question about a
// surprising refusal is what the profile actually said.
func seatbeltProfileFile(t *testing.T, f seatbeltFixtures) string {
	t.Helper()
	profile := macosuser.SeatbeltProfile(f.ws, "", []string{"vendored"})
	path := filepath.Join(t.TempDir(), "session.sb")
	if err := os.WriteFile(path, []byte(profile), 0o644); err != nil {
		t.Fatalf("writing the profile to %s: %v", path, err)
	}
	t.Logf("Seatbelt profile under test (%s):\n%s", path, profile)
	return path
}

// runScript runs one shell script, optionally wrapped in a prefix argv, and returns its
// combined output and exit code.
//
// COMBINED, because the sandbox's refusal arrives on stderr ("Operation not permitted")
// and the case's evidence arrives on stdout; a failure message that carried only one of
// them would send a reader to the runner to see the other.
//
// Stdin is an empty PIPE and never the default /dev/null — see the file header:
// /dev/null is a device vnode, so `isatty(0)` on it is now a denied file-ioctl.
func runScript(t *testing.T, script string, prefix []string) (string, int) {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	argv := append(append([]string{}, prefix...), "/bin/sh", "-c", script)
	cmd := exec.CommandContext(ctx, argv[0], argv[1:]...)
	// FROM "/", NEVER THE PACKAGE DIRECTORY. A runner checks this repo out under
	// /Users/runner/work, which the profile's /Users read deny covers with nothing to
	// re-allow it — so a shell inheriting that cwd can fail to resolve its own $PWD, and
	// the case would report a refusal it never asked for. "/" is read-allowed by the
	// base policy and is the same ground for the bare control.
	cmd.Dir = "/"
	cmd.Stdin = strings.NewReader("")
	out, err := cmd.CombinedOutput()
	if ctx.Err() != nil {
		t.Fatalf("`%s` did not finish within 60s", strings.Join(argv, " "))
	}
	rc := 0
	if err != nil {
		var ee *exec.ExitError
		if errors.As(err, &ee) {
			rc = ee.ExitCode()
		} else {
			t.Fatalf("running `%s`: %v", strings.Join(argv, " "), err)
		}
	}
	return string(out), rc
}

// sh single-quotes a path for /bin/sh. The fixture paths are ours and hold no quotes,
// but a script built by concatenation is a script that grows a space one day.
func sh(s string) string { return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'" }
